### ISSUE TITLE
Update pubspec on Dart pub

### ISSUE THREAD

**Issue by ja2375** [brianegan/chewie#101]
Pubspec shows `video_player: ">=0.7.0 <0.8.0"` **_on Dart pub_** which does not allow to upgrade the video_player plugin.

**Comment by cbenhagen** [comment]
Thanks, we will release a new version as soon as #99 is merged. Until then you could can use this git repo in your `pubspec.yaml`.

**Comment by ja2375** [comment]
Ok, thank you!
