### ISSUE TITLE
Can not pause video from lanscape

### ISSUE THREAD

**Issue by vudaoxa** [brianegan/chewie#103]
This is my widget: 
```
WillPopScope(
      child: Stack(children: <Widget>[
        _buildView(image),
      ]),
      onWillPop: () {
        _videoController?.pause();
        return new Future.value(true);
      },

```
When press back button to previous screen, I want to pause video.
- In portrait, it work normally
- But after from lanscape->portrait, press back -> it failed.
Please help me, thanks.

**Comment by cbenhagen** [comment]
Which chewie version are you using? If this still is an issue with version 0.9.0, please provide a full sample `lib/main.dart` that I can copy into a fresh flutter project.

**Comment by vudaoxa** [comment]
I am using version 0.8.0. It happen the same with version 0.9.0 (more errors when fullscreen)
This is my file
`import 'package:cached_network_image/cached_network_image.dart';
import 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';
import 'package:photo_view/photo_view.dart';
//import 'package:sunshine_housing/models/models.dart';
import 'package:video_player/video_player.dart';

VideoPlayerController _videoController;

List<Container> buildImage(BuildContext context, List<String> images) {
  return images.map((p) {
    var container = Container(
        child: new GestureDetector(
            onTap: () => _showImage(context, p),
            child:
            Stack(alignment: const Alignment(0.0, 0.0), children: <Widget>[
              Container(
                width: double.infinity,
                padding:
                const EdgeInsets.only(top: 15.0, left: 15.0, right: 15.0),
                child: ClipRRect(
                    borderRadius: BorderRadius.all(Radius.circular(10.0)),
                    child: new CachedNetworkImage(
                      imageUrl: p,
                      fit: BoxFit.cover,
                      errorWidget: Material(
                          child: Image.asset(
                            'images/noimage.png',
                          )),
                    )),
              ),
              
            ])));
    return container;
  }).toList();
}

void _showImage(BuildContext context, String image) {
  final pageRoute = MaterialPageRoute(builder: (context) {
    return WillPopScope(
      child: Stack(children: <Widget>[
        _buildView(image),
        GestureDetector(
            onTap: () {
              _dispose();
              Navigator.pop(context);
            },
            child: Container(
                margin: EdgeInsets.only(top: 35.0, left: 15.0),
                child: Icon(
                  Icons.arrow_back,
                  size: 27.0,
                  color: Colors.grey[50],
                )))
      ]),
      onWillPop: () {
        _dispose();
        return new Future.value(true);
      },
    );
  });
  Navigator.of(context).push(pageRoute);
}

Widget _buildView(String image) {
      return Chewie(
        _videoController = VideoPlayerController.network(
            'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'),
        aspectRatio: 3 / 2,
        autoPlay: true,
      );
}

void _dispose() {
  _videoController?.pause();
}
`

`class ImageByRoomCdState extends State<ImageByRoomCd> {
  @override
  Widget build(BuildContext context) {
    return AppLoading(builder: (context, status) {
      return status[1]
          ? ErrorPage(onRetry: widget.onRetry)
          : status[0]
              ? LoadingIndicator(key: Key('__statsLoading__'))
              : new Container(
                  child: new Container(
                    color: Colors.white70,
                    child: new ListView(
                      padding: EdgeInsets.only(bottom: 10.0),
                      shrinkWrap: true,
                      children: <Widget>[
                        new Column(
                          children: buildImage(context, widget.image),
                        )
                      ],
                    ),
                  ),
                );
    });
  }
}
`

**Comment by cbenhagen** [comment]
Please try to reduce the issue to a very minimal example which does not depend on any plugins or other code of yours. Only what is needed to reproduce the issue. Also please surround your code like so to make it readable for others:
````
```dart
class YourClass {
}
```
````

**Comment by vudaoxa** [comment]
Can I send you images  via your email?
note: images of video_player's debugging.

**Comment by cbenhagen** [comment]
You can upload images here. If anyone has the same issue and lands here it would be good if he can follow the full conversation.

**Comment by cbenhagen** [comment]
You mention video_player debugging. Please try to reproduce this without chewie.

**Comment by vudaoxa** [comment]
I just created a demo here, please check that:
https://github.com/vudaoxa/chewie_demo

**Comment by cbenhagen** [comment]
Thank you for the demo project. I am sorry, it is still unclear to me what you are trying to achieve. If you want to be able to come back to the same video and watch from where you left you need to use the same `VideoPlayerController`. [Here](https://github.com/vudaoxa/chewie_demo/blob/master/chewie_demo/chewie_demo/lib/media.dart#L37-L38) you are recreating a new `VideoPlayerController` every time the user clicks on 'Click to play'. The video will then restart from the beginning.

If you want to come start the video where you paused it, I would suggest to put your `_videoController` in the state of some statefulWidget like `ImageByRoomCd` create a new Media widget and then disable `autoPlay` and `autoInitialize` in Chewie. Please also make sure to dispose the `_videoController` by overriding the dispose method.

A quick and dirty version of this could look something like this:
```dart
import 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class ImageByRoomCd extends StatefulWidget {
  @override
  State createState() => ImageByRoomCdState();
}

class ImageByRoomCdState extends State<ImageByRoomCd> {
  VideoPlayerController _videoController;

  @override
  Widget build(BuildContext context) {
    return new Container(
        alignment: Alignment.center,
        child: new GestureDetector(
          onTap: () {
            _videoController.play();
            _showImage("");
          },
          child: new Text(
            "Click to play",
          ),
        ));
  }

  @override
  void dispose() {
    _videoController.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _videoController = VideoPlayerController.network(
        'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4')
      ..initialize();
  }

  Widget _buildView(String image) {
    //todo fix bug: can not pause video after exit fullscreen
    return Chewie(
      _videoController,
      aspectRatio: 3 / 2,
      autoPlay: false,
      autoInitialize: false,
    );
  }

  void _showImage(String image) {
    final pageRoute = MaterialPageRoute(builder: (context) {
      return WillPopScope(
        child: Stack(children: <Widget>[
          _buildView(image),
          GestureDetector(
              onTap: () {
                _videoController?.pause();
                Navigator.pop(context);
              },
              child: Container(
                  margin: EdgeInsets.only(top: 35.0, left: 15.0),
                  child: Icon(
                    Icons.arrow_back,
                    size: 27.0,
                    color: Colors.grey[50],
                  )))
        ]),
        onWillPop: () {
          _videoController?.pause();
          return new Future.value(true);
        },
      );
    });
    Navigator.of(context).push(pageRoute);
  }
}
```

**Comment by cbenhagen** [comment]
You could also save the current position of a VideoPlayerController somewhere in you applications state and then use the `startAt` option of Chewie.

I am closing this issue as I can not see anything wrong with Chewie here. If you have general questions about how to structure your flutter code or how to achieve a certain goal I would suggest to post the question on StackOverflow or one of the communities mentioned here: https://flutter.io/community.

**Comment by vudaoxa** [comment]
Thanks for your support. 
The bug is from my view structure, not from Chewie.
I have fixed this by:

` Widget _buildView(SImage image) {
return Scaffold(
          backgroundColor: Colors.black,
          body: Center(
            child: _controller.value.initialized
                ? Chewie(
                    _controller,
                    aspectRatio: 3 / 2,
                    autoPlay: true,
                  )
                : Container(),
          ),
        );
}`
