### ISSUE TITLE
bufferedColor not showing on Android

### ISSUE THREAD

**Issue by ThinOfSnowDance** [brianegan/chewie#104]
_chewieController = ChewieController(
      videoPlayerController: _videoPlayerController1,
      aspectRatio: 3 / 2,
      autoPlay: true,
      looping: true,
      // Try playing around with some of these other options:

      // showControls: false,
       materialProgressColors: ChewieProgressColors(
         playedColor: Colors.red,
         handleColor: Colors.blue,
         backgroundColor: Colors.grey,
         bufferedColor: Colors.lightGreen,
       ),
      // placeholder: Container(
      //   color: Colors.grey,
      // ),
//       autoInitialize: true,
    );

If buffer is to be achieved, what should be done?
![djn 6 ceuln jfu y l](https://user-images.githubusercontent.com/28644545/51811647-dc94b100-22e8-11e9-8656-f913d4556872.png)

**Comment by cbenhagen** [comment]
Hi, thank you for reporting this issue. Chewie is doing the right thing here, but it does not get the correct data from the underlying VideoPlayer plugin. I opened issues for the root problems [here](https://github.com/flutter/flutter/issues/27178) and [here](https://github.com/flutter/flutter/issues/27179). You can find my proposed fix [here](https://github.com/flutter/plugins/pull/1123).

Closing this issue as Chewie is doing everything as expected here.

**Comment by cbenhagen** [comment]
@ThinOfSnowDance please add a +1 reaction (using the button on the issue) to both issues linked above and the PR to give it some more priority.

**Comment by ThinOfSnowDance** [comment]
Thank you very much for your answer!video_player
