### ISSUE TITLE
Hidden status bar problem

### ISSUE THREAD

**Issue by ThinOfSnowDance** [brianegan/chewie#106]
The first:
I added 
```
 SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);
```
 to the initState of Widget.
It can be hidden.
![image](https://user-images.githubusercontent.com/28644545/51880785-8fc9dc80-23b3-11e9-9dd0-92e8efd911bb.png)

Then the full screen comes back here again.

![image](https://user-images.githubusercontent.com/28644545/51880875-ec2cfc00-23b3-11e9-8235-54bb8bfbb11f.png)
You can't hide it.

I tried to add listening

```
    _chewieController = ChewieController(
      videoPlayerController: _videoPlayerController1,
      aspectRatio: 3 / 2,
      autoPlay: true,
      looping: true,
//       autoInitialize: true,
    );
    _chewieController.addListener(()=>(
      //  SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom])
        !_chewieController.isFullScreen?SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]):null
    )  );
    
```

The Listener was found to be executed, but it was not hidden.
And switching from full-screen to non-full-screen will perform two callbacks
use version is:  chewie: ^0.9.0

**Comment by cbenhagen** [comment]
Hi, thank you for reporting this. I an option to set the prefered UI overlays after exiting full screen in 0da55825608afc1b262fc5a2d3f0ff79fc7a149f. This has been released in chewie 0.9.2.

**Comment by cbenhagen** [comment]
You can set it like this:
```dart
final chewieController = ChewieController(
  videoPlayerController: videoPlayerController,
  aspectRatio: 3 / 2,
  autoPlay: true,
  looping: true,
  systemOverlaysAfterFullScreen: [SystemUiOverlay.bottom]
);
```

**Comment by ThinOfSnowDance** [comment]
Thank you very much for your answer!
  But after I added systemOverlaysAfterFullScreen: [SystemUiOverlay.bottom]
The first time won't hide
Is it the first time you still need to add     SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);  to initState?
