### ISSUE TITLE
Screen is only kept on when in fullscreen

### ISSUE THREAD

**Issue by snaeji** [brianegan/chewie#107]
It seems like the screen is only kept on during fullscreen mode.

When i press the fullscreen button i get a print stating that Screen is not kept on, and Screen is kept on when back in fullscreen mode.

Maybe there is some logic behind it but i at least can't figure it out.

This is how i initialise Chewie:

      fullScreenByDefault: false,
      allowedScreenSleep: false,

**Comment by cbenhagen** [comment]
Well, looking at the API documentation it is doing exactly what it says:
```dart
/// Defines if the player will sleep in fullscreen or not
final bool allowedScreenSleep;
```

I don't think it makes sense to keep the screen on when not in full screen mode. But if you need this behaviour in your app you can simply use the Screen plugin:
```dart
Screen.keepOn(true);
```

**Comment by snaeji** [comment]
I should have read the API documentation.. Thanks! Awesome plugin btw...
