### ISSUE TITLE
Compatibility issue with the latest video_player 0.10.0

### ISSUE THREAD

**Issue by willvlad** [brianegan/chewie#108]
Because chewie 0.9.3 depends on video_player >=0.7.0 <0.9.0 and no versions of chewie match >0.9.3 <0.10.0, chewie ^0.9.3 requires video_player >=0.7.0 <0.9.0.

So, because ddd depends on both chewie ^0.9.3 and video_player ^0.10.0, version solving failed.

**Comment by hamidabdulmalik** [comment]
Same here, we need to fix this. I am supposed to ship out by tomorrow and this is not helping matters

**Comment by cbenhagen** [comment]
Added support in version 0.9.4.
