### ISSUE TITLE
Use of the VideoPlayerController inside Chewie

### ISSUE THREAD

**Issue by stemuk** [brianegan/chewie#11]
I have two questions about chewie (which are tecnically speaking not 'issues') that i feel like would not make sense on github or gitter because of their specific nature. It would be great if you could help me out here! :) 

That said, my current structure is simplified the following

```
new FutureBuilder<DocumentSnapshot>(
...
new Chewie(
	controller,
	aspectRatio: 16 / 9,
	autoPlay: true,
	looping: false,
	placeholder: new Container(
	color: Colors.grey,
	),
	autoInitialize: true,
),
),
...
  @override
  void initState() {
    controller = new VideoPlayerController(
        'https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.mp4');

    super.initState();
  }
```
As seen above, the controller is outsiede the scope of the Futurebuilder, so no data from the DocumentSnapshot can be used as a parameter for the VideoPlayerController.

So now my question: is it possible to implement the VideoPlayerController inside the Chewie widget, or can I maybe pass a value from the FutureBuilder down to the VideoPlayerController any other way? Any help would be highly appreciated!

On a sidenote, do you know whether it is possible to rotate the currently watched video into landscape mode as soon as the Fullscreen mode is activated? This way more screen real estate would be used and the user would be incentivised to rotate his/her device.

**Comment by brianegan** [comment]
Hey @stemuk! Thanks for writing in :) We could consider changes to Chewie so it only took a Video URL rather than a Controller, but would it end up being much different in the end? In this example, would it be possible to do something like this?

```dart
new FutureBuilder<DocumentSnapshot>(
  future: firestore.getDocument()
  builder: (context, snapshot) {
    return new Chewie(new VideoController(snapshot.data['url']));
  },
);
```

I think your second suggestion actually makes a lot of sense. That's generally the default for most apps. I've created a separate issue to track that one! Any help implementing that functionality would be appreciated!

https://github.com/brianegan/chewie/issues/12

**Comment by stemuk** [comment]
Thanks a lot for your answer @brianegan ! Yes, the example you mentioned would be possible if the state of Chewie would also be updated. 

Looking the chewie-player.dart file the _buildFullScreenVideo Widget would have to be modified to rotate its children PlayerWithControls, maybe with https://docs.flutter.io/flutter/widgets/RotationTransition-class.html ? I have yet to learn animations in flutter but I will try to look into it more tomorrow.

**Comment by brianegan** [comment]
@stemuk Ah yes, perhaps I should check in the `didUpdateWidget` method if the streamController has changed. If the controller is different than the previous controller, stop / teardown the previous controller and rebuild it with the new properties.

**Comment by brianegan** [comment]
Heya @stemuk, I found some time to update Chewie today! It should include FullScreen -> Landscape Mode support on Andorid (iOS does not automatically rotate to Full Screen) and also supports providing a new `VideoPlayerController` to Chewie and it will properly switch / restart the vid if the URL / Asset path changes.

**Comment by fukemy** [comment]
version 0.4.0 make my app crash when 0.3.0 work normally. Log

```

E/MethodChannel#flutter.io/videoPlayer(16128): Failed to handle method call
E/MethodChannel#flutter.io/videoPlayer(16128): java.lang.NullPointerException: uriString
E/MethodChannel#flutter.io/videoPlayer(16128): 	at android.net.Uri$StringUri.<init>(Uri.java:476)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at android.net.Uri$StringUri.<init>(Uri.java:466)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at android.net.Uri.parse(Uri.java:438)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1220)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1187)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at io.flutter.plugins.videoplayer.VideoPlayerPlugin$VideoPlayer.<init>(VideoPlayerPlugin.java:57)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at io.flutter.plugins.videoplayer.VideoPlayerPlugin.onMethodCall(VideoPlayerPlugin.java:210)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at android.app.ActivityThread.main(ActivityThread.java:7406)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/MethodChannel#flutter.io/videoPlayer(16128): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/flutter (16128): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (16128): PlatformException(error, uriString, null)
E/flutter (16128): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:547:7)
E/flutter (16128): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (16128): <asynchronous suspension>
E/flutter (16128): #2      VideoPlayerController.initialize (package:video_player/video_player.dart:166:59)
E/flutter (16128): <asynchronous suspension>
E/flutter (16128): #3      _MaterialControlsState._playPause.<anonymous closure> (package:chewie/src/material_controls.dart:296:29)
E/flutter (16128): #4      State.setState (package:flutter/src/widgets/framework.dart:1125:30)
E/flutter (16128): #5      _MaterialControlsState._playPause (package:chewie/src/material_controls.dart:287:5)
E/flutter (16128): #6      _MaterialControlsState._buildHitArea.<anonymous closure> (package:chewie/src/material_controls.dart:136:17)
E/flutter (16128): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (16128): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (16128): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
E/flutter (16128): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (16128): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (16128): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (16128): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter (16128): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (16128): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (16128): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (16128): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (16128): #18     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (16128): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

**Comment by fukemy** [comment]
thanks you. it work now

**Comment by RoughIndustries** [comment]
Using chewie 0.7.0. I am doing as stated above for using a snapshot to populate a videoplayercontroller with a future builder. If I navigate away doing nothing else but the initial build method the chewie/videoplayercontroller  seems to dispose correctly.  If however I even do one full screen expand and then go back to regular there is a chewie/videoplayercontroller that seems to keep running and I hear the audio still even though I am not on that page.  I have tried to track my controllers and force the dispose on pages dispose but i dont know why it keeps playing. Thoughts?

**Comment by tikodrack** [comment]
Hello,

I am having the same curious circumstance, that when navigating away from the video, the audio keeps on running... then, when navigating back again to the same video page, the video and the audio start playing simultaneously with the former audio, as there's seemingly no way to stop it...

My dart file presently looks as follows:
`import 'package:chewie/chewie.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class EstrategiasPage extends StatefulWidget {
  @override
  _EstrategiasPageState createState() => new _EstrategiasPageState();
}

class _EstrategiasPageState extends State<EstrategiasPage> {
  TargetPlatform _platform;
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = new VideoPlayerController.network(
      'http://costari.ca/apps/iphe/videos/IPHE_metodologias_y_estrategias_bilingues.mp4',
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Estrategias Bilingües'),
    backgroundColor: Colors.indigo[900],
      ),
      body: new Column(
        children: <Widget>[
          new Expanded(
            child: new Center(
              child: new Chewie(
                _controller,
                aspectRatio: 3 / 2,
                autoPlay: true,
                looping: false,
                showControls: true,

                // Try playing around with some of these other options:

                // showControls: false,
                // materialProgressColors: new ChewieProgressColors(
                //   playedColor: Colors.red,
                //   handleColor: Colors.blue,
                //   backgroundColor: Colors.grey,
                //   bufferedColor: Colors.lightGreen,
                // ),
                // placeholder: new Container(
                //   color: Colors.grey,
                // ),
                // autoInitialize: true,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
`

I understand that you have successfully solved this issue:

> Solved. I had my controller list in my widget and not in my state. I was trying to access the widget.controllers in the state and do a dispose which wasn't working. I moved the controller list to the state and dispose it there. Good to go.

but them, I am still a newbie to flutter and don't yet seem to understand how to implement your solution in my case... could you please be so kind to further explain the procedure?

**thank you immensely !!!**

Daniel
