### ISSUE TITLE
Progress bar goes out of the interface when playing live resources

### ISSUE THREAD

**Issue by feilongfl** [brianegan/chewie#113]
![photo_2019-02-11_12-26-09](https://user-images.githubusercontent.com/10269596/52546223-7041a380-2df8-11e9-8173-64c493451550.jpg)

Progress bar goes out of the interface when playing live resources.

**Comment by feilongfl** [comment]
I fix this issue and make a pr for you at https://github.com/brianegan/chewie/pull/115

**Comment by brianegan** [comment]
Thanks much!
