### ISSUE TITLE
error for internet connection

### ISSUE THREAD

**Issue by parsibox** [brianegan/chewie#114]
hi
i have error when internet connection is week

![image](https://user-images.githubusercontent.com/12513476/52549830-72046a80-2dea-11e9-92cd-cd45857e30b0.png)

**Comment by hamidabdulmalik** [comment]
I had same error, after giving it some thought, I just reverted to the raw flutter video player. I am not sure the author of chewie has the time to address this issue.

**Comment by brianegan** [comment]
Oh dang, that's not looking good. Thanks for the report!

Also, @hamidabdulmalik  -- Definitely constrained on time :) That said, always happy to accept PRs to improve it for everyone!

**Comment by hamidabdulmalik** [comment]
@brianegan it's ok. I understand. Your product is the only cool one out there. That said, I am waiting for a fix so that I can switch back lol. Great job.

**Comment by parsibox** [comment]
please fix this
we have time limit

**Comment by hamidabdulmalik** [comment]
@parsibox please check again. I think he upgraded.

**Comment by brianegan** [comment]
Hey hey, I found some time this weekend to work on a fix. I've put up a PR with instructions on how to use it here: #126 

Please let me know if that works out and I'll publish it to the rest of the community

**Comment by parsibox** [comment]
thanks
