### ISSUE TITLE
One suggestion

### ISSUE THREAD

**Issue by msterzhang** [brianegan/chewie#116]
Hi, thank you very much for your work. I have a suggestion to add a transparent function, as shown below, so that we can get a bigger view.

![22](https://user-images.githubusercontent.com/31364579/52719570-d8eb7480-2fe0-11e9-8397-2e840dfc8b9d.jpg)

**Comment by brianegan** [comment]
Hey there -- that looks pretty cool, indeed! That said, I don't think we should provide this as a constructor option, but rather I think this design could actually live as it's own package!

If you look at the ChewieController, you can now pass through `customControls`. To keep the core library slim, we only maintain two Custom Controls out of the box: Material and Cupertino. 

However, you could definitely create your own package on `pub`, such as `chewie_transparent_ui`. It could contain a set of Custom Controls that implement the Design you've got above! Then, anyone who wants to use it would simply need to import your package in their `pubspec` and use them when they create the ChewieController!

**Comment by msterzhang** [comment]
Okay, thank you for your quick response.

**Comment by cbenhagen** [comment]
You can also use `MaterialControls` from chewie and just wrap it in an `Opacity` widget.
