### ISSUE TITLE
Support for video player version 10.0+

### ISSUE THREAD

**Issue by vijaykanta** [brianegan/chewie#117]
I don't know exactly why this plugin cannot work with video player 10+. I had upgraded my android versions to Android X and they required video player to be 10.0+, but I have Chewie player in many parts of the project, and hence I am stumbled upon this hurdle.

Is there any immediate availability of new Chewie supporting video player 10.0+?

**Comment by brianegan** [comment]
Oh dang, that looks like it was a regression we meant to ship. The dependency constraints have been lifted, and you can use `0.9.6` which supports 10+
