### ISSUE TITLE
Cannot leave fullscreen when button is disabled

### ISSUE THREAD

**Issue by ja2375** [brianegan/chewie#119]
I am building an app which launches a chewie video in a new route. The route only contains the video, therefore i set it to fullscreen by default and disabled the player fullscreen button (using `allowFullscreen: false`). Then i noticed that users cannot use the back button on the phone to go back because it is locked.
Furthermore, iPhones/iPad don't have a back button.

My suggestion is to add a top bar to the player controls (i mean, above the play button, at the top of the screen) that would allow to put a back button in there to close the video (or exit fullscreen).

Letting users use the built in back button wouldn't be enough because it would be useless on iOS.

**Comment by brianegan** [comment]
Hey there :) It sounds like ya need a bit of different functionality than Chewie offers out of the box that is specific to your project's requirements.

I'll leave the issue open for now to see if more folks also need this functionality, but in the meantime, you can always enhance Chewie's built-in controls by providing your own `customControls` Widget. That widget could replace the normal controls in full screen mode for your app and is completely customizable. You can create a button to exit fullscreen like so:

```
RaisedButton(
  onPressed: () => ChewieController.of(context).exitFullScreen();
);
```

**Comment by ja2375** [comment]
Thanks! I will give it a try :)
