### ISSUE TITLE
Will and When this plugin migrates to Android X?

### ISSUE THREAD

**Issue by harshapulikollu** [brianegan/chewie#121]
Just wanted to know any changes of migrating this plugin to android X.

**Comment by brianegan** [comment]
Hey there -- the latest version of Chewie `0.9.6` supports the latest version of the `video_player` plugin: `0.10.x`. The 0.10.x branch of the `video_player` plugin is based on AndroidX components.

All Chewie provides is the UI playback controls. The `video_player` plugin does all of the hard work, so as long as you're using the latest Chewie you should be all good.
