### ISSUE TITLE
Is there an event listener that happens when you press the full screen button on the chewie?

### ISSUE THREAD

**Issue by kyungjoongo** [brianegan/chewie#122]
Is there an event listener that happens when you press the full screen button on the chewie?

**Comment by brianegan** [comment]
Yes there is! The `ChewieController` is a `Listenable`. You can listen to the ChewieController for changes:

```
final controller = ChewieController(...);
controller.addListener(() {
  if (controller.isFullScreen) {
    doSomeStuff();
  } 
});
```
