### ISSUE TITLE
Support for custom headers and bearer token

### ISSUE THREAD

**Issue by pepie** [brianegan/chewie#124]
Chewie 0.9.6
It doesn't seem possible to pass custom headers and/or bearer tokens.

Example:
var url = "https://my_secure_path/stream/video1";
```

     _videoPlayerController = new VideoPlayerController.network(url);
    ChewieController _chewieController = new ChewieController(
        videoPlayerController: _videoPlayerController,
        aspectRatio: 16/9,
        autoPlay: true,
        autoInitialize: true,
        looping: false,
        showControls: true,
        fullScreenByDefault: true,
        deviceOrientationsAfterFullScreen: [DeviceOrientation.portraitUp],
        materialProgressColors: new ChewieProgressColors(
            backgroundColor: Colors.orange
        ),
        placeholder: placeholderImage
    );

    return new Chewie(
      controller: _chewieController,
    );
```
Playback would fail with:
```Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.```

Please advise.

**Comment by cbenhagen** [comment]
This is currently not possible and has to be implemented in the video_player plugin. There are two open PR in this issue: https://github.com/flutter/flutter/issues/16466

I am closing this as there is nothing to do in Chewie.

**Comment by HiroyukiTamura** [comment]
now video_player [v2.1.0](https://pub.dev/packages/video_player/changelog#210) supports custom http header
