### ISSUE TITLE
FullScreenByDefault forces fullscreen after exiting fullscreen

### ISSUE THREAD

**Issue by snaeji** [brianegan/chewie#132]
FullScreenByDefault forces fullscreen after exiting fullscreen.
The api states that it should only define how it starts:
Defines if the player will start in fullscreen when play is pressed

So basicly when i press the button to exit fullscreen mode, it goes immediately back to fullscreen mode.

```    if (fullScreenByDefault) {
      videoPlayerController.addListener(() async {
        if (videoPlayerController.value.isPlaying && !_isFullScreen) {
          enterFullScreen();
        }
      });
    }
```
I think this code here is the culprit, when i comment it out everything works fine.

My settings are:

```
    chewieController = ChewieController(
      videoPlayerController: widget.controller,
      aspectRatio: 16 / 9,
      autoInitialize: true,
      fullScreenByDefault: true,
      looping: true,
      autoPlay: true
    );
```

Maybe the fault is on my side?

**Comment by localpcguy** [comment]
Submitted a PR that should fix this by only running the listener until it is executed once (i.e. on initial play, if `fullScreenByDefault` make the app full screen and cancel the listener. After that, if the user leaves full screen, the app should respect the user's choice and not try to go back to full screen.
