### ISSUE TITLE
Cannot play video fullscreen in portrait orientation

### ISSUE THREAD

**Issue by MichaelFerrier** [brianegan/chewie#137]
When entering fullscreen, the video rotates to landscape orientation, even though it is a portrait video with aspect ratio 9 / 16, and even though its deviceOrientationsAfterFullScreen list has been set to include only the two portrait orientations.

This problem occurs on Android. In iOS, portrait fullscreen works correctly. I don't know if this issue may be related to issue 86: https://github.com/brianegan/chewie/issues/86

Does anyone know how to get a video to play fullscreen in portrait orientation?

My ChewieController is set up as follows:

```
chewieController = ChewieController(
            videoPlayerController: videoPlayerController,
            aspectRatio: 9 / 16,
            autoPlay: true,
            fullScreenByDefault: false,
            looping: false,
            deviceOrientationsAfterFullScreen: [
              DeviceOrientation.portraitUp,
              DeviceOrientation.portraitDown
            ],
            placeholder: new Center(
              child: RVTApp.BuildActivityIndicator(context),
            ),
          );
```

Thank you.

**Comment by sfaujour** [comment]
Hey, if you want to play it just in portrait you could use it like this:

add `auto_orientation: ^0.0.2` to your pubspec.yml

create a custom scaffold like this:

```
class _VideoScaffoldState extends State<VideoScaffold> {

  @override
  void initState() {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);
    AutoOrientation.landscapeMode();
    super.initState();
  }

  @override
  dispose(){
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);
    AutoOrientation.portraitMode();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}

and use it with the new routePageBuilder (available >= 0.9.7)

```
chewieController = ChewieController(
            videoPlayerController: videoPlayerController,
            aspectRatio: 9 / 16,
            autoPlay: true,
            fullScreenByDefault: false,
            looping: false,
            deviceOrientationsAfterFullScreen: [
              DeviceOrientation.portraitUp,
              DeviceOrientation.portraitDown
            ],
            placeholder: new Center(
              child: RVTApp.BuildActivityIndicator(context),
            ),
            routePageBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondAnimation, provider) {
                return AnimatedBuilder(
                    animation: animation,
                    builder: (BuildContext context, Widget child) {
                        return VideoScaffold(
                            child: Scaffold(
                                resizeToAvoidBottomPadding: false,
                                body: Container(
                                    alignment: Alignment.center,
                                    color: Colors.black,
                                    child: provider,
                                ),
                            ),
                        );
                    },
                );
            }
    );
```

**Comment by MichaelFerrier** [comment]
> Hey, if you want to play it just in portrait you could use it like this:

Thank you @sfaujour for the detailed explanation on how to do this, I will give it a try!

(And may I suggest to the keepers of Chewie that perhaps there could be added a more intuitive way to play a portrait video in portrait orientation :) )

**Comment by sfaujour** [comment]
Can this be closed @MichaelFerrier @brianegan  ? :)

**Comment by MichaelFerrier** [comment]
> Can this be closed @MichaelFerrier @brianegan ? :)

This is solved to my satisfaction, so it seems to me it can be closed if no further change of behavior is planned for this issue. Thank you very much for the help! :)

However IMHO, playing a portrait video and including only the portrait orientations in the deviceOrientationsAfterFullScreen list should be enough to ensure that the video plays in portrait orientation, without requiring an additional package, custom scaffold, etc.

**Comment by caothang1183** [comment]
@sfaujour This is awesome! Thanks for your guiding

**Comment by jsgalarraga** [comment]
I fixed the issue much easier than the solution above, and I don't know if there is any drawback, but it could be implemented in the master branch.

Inside `chewie_player.dart`, in the method `_pushFullScreenWidget` orientation can be dependant on the aspect ratio. Being in portrait mode when aspect ratio lower or equal than 1 and landscape otherwise:
`
SystemChrome.setEnabledSystemUIOverlays([]);
    if (isAndroid) {
      if (widget.controller.aspectRatio <= 1){
        SystemChrome.setPreferredOrientations([
          DeviceOrientation.portraitUp,
          DeviceOrientation.portraitDown,
        ]);
      } else {
        SystemChrome.setPreferredOrientations([
          DeviceOrientation.landscapeLeft,
          DeviceOrientation.landscapeRight,
        ]);
      }
    }
`
