### ISSUE TITLE
Using Chewie with Hero's

### ISSUE THREAD

**Issue by videah** [brianegan/chewie#143]
Chewie can't currently be used with Hero widgets because it already uses one internally.

![image](https://user-images.githubusercontent.com/4761786/56044490-3416ba80-5d37-11e9-9447-8c7bccb46cc2.png)

**Comment by localpcguy** [comment]
Just ran into this also, what is the utility of the `Hero` tag in this case? Is it to allow for animating the video from the inline view to fullscreen view?

**Comment by localpcguy** [comment]
any update on this and potentially getting the PR mentioned merged @brianegan?
