### ISSUE TITLE
I can't able to add more than 4 videos

### ISSUE THREAD

**Issue by Alidhuniya** [brianegan/chewie#146]
I/flutter (21551): #133    _invoke (dart:ui/hooks.dart:209:10)
I/flutter (21551): #134    _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (21551): (elided 3 frames from package dart:async)
I/flutter (21551): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (21551): Another exception was thrown: A VideoPlayerController was used after being disposed.
I/flutter (21551): Another exception was thrown: A VideoPlayerController was used after being disposed.
I/flutter (21551): Another exception was thrown: A VideoPlayerController was used after being disposed.
I/flutter (21551): Another exception was thrown: A VideoPlayerController was used after being disposed.
I/flutter (21551): Another exception was thrown: A VideoPlayerController was used after being disposed.

**Comment by Dhua-v** [comment]
You must create seperate videocontrollers for each player.
Hope It solves the problem.
