### ISSUE TITLE
Question : when exit fullscreen , the player still running on the background

### ISSUE THREAD

**Issue by MessiMercy** [brianegan/chewie#155]
When i enter the full screen mode , it works right . 
But when i tap the button to exit full screen mode ,  
the voice is still playing , but the original page`s controller has reload ，
and i cant stop the voice except shutdown this app .
here is my code : 
```
class VideoApp {
  static produceVideo(BuildContext context, String url) {
    var videoPlayerController = new VideoPlayerController.network(url);
    ChewieController videoWidget = ChewieController(
        videoPlayerController: videoPlayerController,
        aspectRatio: 3 / 2,
        autoPlay: false,
        autoInitialize: true,
        allowFullScreen: true,
        placeholder: new Container(
          color: Colors.grey,
        ),
    );
    return Chewie(
      controller: videoWidget,
    );
  }
}
```

  ```
_video(String url) {
    Chewie produceVideo = VideoApp.produceVideo(context, url);
    _controller = produceVideo.controller;
    _chewie = produceVideo;
    return Container(
      child: produceVideo,
      color: Colors.white,
    );
  }
```

**Comment by zf19820621** [comment]
Make sure that VideoPlayerController and ChewieController is used with one instance, so you should call dispose when use them for another video.

**Comment by qiaoyhh** [comment]
@override
  void initState() {
  var videoPlayerController = new VideoPlayerController.network(url);
    ChewieController videoWidget = ChewieController(
        videoPlayerController: videoPlayerController,
        aspectRatio: 3 / 2,
        autoPlay: false,
        autoInitialize: true,
        allowFullScreen: true,
        placeholder: new Container(
          color: Colors.grey,
        ),
    );
}

That's it@MessiMercy

**Comment by Azandowski** [comment]
how did you fix it?

**Comment by cbenhagen** [comment]
@MessiMercy your class should extend StatefulWidget. You can then setup your controller in initState. A full example can be found here:
https://github.com/brianegan/chewie/blob/master/example/lib/main.dart

Please comment if you still have issues.
