### ISSUE TITLE
Chewie usage without Material resources

### ISSUE THREAD

**Issue by frendyguo** [brianegan/chewie#158]
Is it possible to use Chewie widget without having to import built-in Material dependencies? I am trying to develop a non material Flutter app
Currently I got errors like so when implementing Chewie player in my Flutter app
`[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!`

**Comment by guopeng1994** [comment]
how do you resolve it ?

**Comment by frendyguo** [comment]
@guopeng1994 
After dive deep into the library, I finally decided to rewrite the whole library to suit my need. In which case I removed any usage of `Material` package, since as it turns out, it requires `Material` / `Cupertino` only for their icon widgets

**Comment by cbenhagen** [comment]
You could also just replace the controls by setting the `customControls` property of the `ChewieController`. I am gonna close this issue as I don't think there is anything to do in Chewie. Please comment if you think there is.
