### ISSUE TITLE
How to use Cupertino Controls on android

### ISSUE THREAD

**Issue by NestorDevs** [brianegan/chewie#159]
hello I find the plugins incredible ... I'm new to flutter but my question is how do I define the CupertinoControl instead of the android controls? what I want to say is that I do not know where to use that attribute so that instead of showing the material controls I use the ones of cupertino on an android device. thank you very much if you can help me...
so i have the driver

![carbon (9)](https://user-images.githubusercontent.com/36705339/58361977-6c460880-7e60-11e9-96e1-bb8a41827743.png)

**Comment by cbenhagen** [comment]
You can wrap the `Chewie` widget in a theme widget with platform set to ios:
```dart
Theme(
  data: ThemeData.light().copyWith(
    platform: TargetPlatform.iOS,
  ),
  child: Chewie(
    controller: _chewieController,
  ),
)
```

**Comment by pradipdabhi** [comment]
`chewieController = ChewieController(
      videoPlayerController: _controller,
      aspectRatio : deviceRatio,
      autoplay : true,
      looping: false,
      allowFullscreen : true,
      customControls:  CupertinoControls(
        iconColor: Colors.amber,
        backgroundColor: Colors.black,
        showPlayButton: false,
      ),
    );*`
