### ISSUE TITLE
Subtitles (CC)

### ISSUE THREAD

**Issue by fanfantasi** [brianegan/chewie#162]
Read file .srt subtitle video streaming, how show subtitle in video streaming.. Please help me?...

**Comment by rakyat-game** [comment]
Duplicate issue, please read #77

**Comment by snaeji** [comment]
You should be able to use this:

https://github.com/snaeji/video_player-0.10.1-3
https://github.com/snaeji/chewie-0.9.7

**Comment by fanfantasi** [comment]
Thanks ya

Pada tanggal Kam, 27 Jun 2019 00.06, snaeji <notifications@github.com>
menulis:

**Comment by cbenhagen** [comment]
Duplicate of #77
