### ISSUE TITLE
Bottom navigation bar stays visible when in a CupertinoPageScaffold

### ISSUE THREAD

**Issue by Toolenaar** [brianegan/chewie#163]
Hi I have a setup in which I have a CupertinoTabScaffold > CupertinoPageScaffold > Column > Chewie

When I want to view the video in fullscreen. The appbar stays visible, which is the default behaviour for a CupertinoPageScaffold. However for a video this is not ideal.

So I tried to alter the ChewiePlayer _pushFullScreenWidget() function  from 

```
await Navigator.of(context).push(route);
```
to

```
await Navigator.of(context,rootNavigator: true).push(route);
```
This seems to work as it now opens the video in fullscreen. However when I try to close the fullscreen view with the fullscreen button, nothing happens.

Any idea how I could solve this ?

**Comment by Toolenaar** [comment]
Off-course after a night of sleep the answer is very easy.

When popping also use the rootnavigator...

```
  Navigator.of(context, rootNavigator: true).pop();
```

🤦🤦🤦

**Comment by ihrankouski** [comment]
Do you know is there any way to achieve this without editing chewie code at the moment?

**Comment by tuanbs** [comment]
I got the same issue. Bottom navigation not hidden when video player in fullscreen. Please help. Thanks.

**Comment by tuanbs** [comment]
I solved this issue by creating an `InvisibleCupertinoTabBar ` thanks to [this solution](https://stackoverflow.com/a/56230540/2328861). Anyway, thanks for this package which is very useful.
