### ISSUE TITLE
Custom navigation?

### ISSUE THREAD

**Issue by mr921112** [brianegan/chewie#164]
Excuse me, I would like to know how to customize the background color of the navigation at the bottom of the player? Can you tell me what to do?

**Comment by jacksun0124** [comment]
I just found Android control was using **dialogBackgroundColor** . If you want change it, you can add Theme widget and change this:
`dialogBackgroundColor: Colors.white.withOpacity(0.5)`

**Comment by cbenhagen** [comment]
If you want to customize more than the color you can also provide your own controls to the `customControls` property of `ChewieController`.
