### ISSUE TITLE
Possible to display play button without seekbar?

### ISSUE THREAD

**Issue by Agraphie** [brianegan/chewie#169]
Hi there,

is it possible to dispaly the play button in the center of the screen without displaying the control bar at the bottom?

**Comment by VictorUvarov** [comment]
You would have to not show the controls and use the overlay widget or create custom controls.
```dart
chewieController = ChewieController(
      ...
      overlay: YourOverlay(),
      customControls: YouCustomControlls(),
      showControls: false,
);

**Comment by Agraphie** [comment]
Thanks. I missed the `overlay` option somehow :)
