### ISSUE TITLE
A VideoPlaverController was used after being disposed.Once you have called dispose() on a VideoplaverController, it can no longer be used.

### ISSUE THREAD

**Issue by 982991084** [brianegan/chewie#170]
![微信图片_20190614180321](https://user-images.githubusercontent.com/22464456/59501717-b6a22e80-8ece-11e9-9bc5-363bbb0b263f.png)

**Comment by dmlzj** [comment]
I have the same problem!

**Comment by js1972** [comment]
Are you using the video player inside a list - if so - what happens is that the list disposes list items as they scroll out of view. What I am doing to get around this is to set the cacheExtent on the List.builder of CustomScrollView (depending on which one you are using) to a really large value like 10000.0. Then you can scroll up and down with heaps of items without issue.

However - if you did have hundreds of items you'll still hit an issue. For me its no problem as I limit my list to 50 items.

**Comment by Mayankk1995** [comment]
So I faced the same problem. I compared it with the example given and I found one very silly error that I was making. It was related to making 'super' calls in initState() and dispose().

`@override
  void initState() {
    super.initState();  //Super should be called at the very beginning of init

    _controller = VideoPlayerController.network(
      'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    );
    _chewieController = ChewieController(
      videoPlayerController: _controller,
      aspectRatio: 3 / 2,
      autoPlay: true,
      looping: true,
    );
  }`

`@override
  void dispose() {
    _controller.dispose();
    _chewieController.dispose();
    super.dispose(); //Super should be called at the very end of dispose
  }`

Let me know if this doesn't solve your issue.

**Comment by khietlam** [comment]
try this 

`
Future<void> _initializePlay(int index) async {
    _controller = VideoPlayerController.asset(videoList[index]);
    _controller.addListener(_controllerListener);
    if (_controller.value.hasError) {
      print(_controller.value.errorDescription);
    }
    _chewieController = ChewieController(
      videoPlayerController: _controller,
      aspectRatio: 9 / 16,
      showControls: false,
      allowedScreenSleep: false,
    );
    _chewieController.setVolume(1.0);
    _initializeVideoPlayerFuture = _controller.initialize();
  }
// and put this code in the place you want to dispose 
 _initializeVideoPlayerFuture = null;
        _controller?.pause()?.then((_) {
          _controller.removeListener(_controllerListener);
          Future.delayed(Duration(seconds: 2));
          _controller.dispose();`

**Comment by VictorUvarov** [comment]
in the example they have:
```dart
@override
  void dispose() {
    _videoPlayerController?.dispose();
    chewieController?.dispose();
    super.dispose();
  }
```

**Comment by kangjinwen** [comment]
> So I faced the same problem. I compared it with the example given and I found one very silly error that I was making. It was related to making 'super' calls in initState() and dispose().
> 
> ```
>   void initState() {
>     super.initState();  //Super should be called at the very beginning of init
>     _controller = VideoPlayerController.network(
>       'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
>     );
>     _chewieController = ChewieController(
>       videoPlayerController: _controller,
>       aspectRatio: 3 / 2,
>       autoPlay: true,
>       looping: true,
>     );
>   }
> 
> @override
>   void dispose() {
>     _controller.dispose();
>     _chewieController.dispose();
>     super.dispose(); //Super should be called at the very end of dispose
>   }
> 
> //Let me know if this doesn't solve your issue.
> ```

TKS, it's worked .

**Comment by Ashwanimvit16** [comment]
> So I faced the same problem. I compared it with the example given and I found one very silly error that I was making. It was related to making 'super' calls in initState() and dispose().
> 
> ```
>   void initState() {
>     super.initState();  //Super should be called at the very beginning of init
>     _controller = VideoPlayerController.network(
>       'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
>     );
>     _chewieController = ChewieController(
>       videoPlayerController: _controller,
>       aspectRatio: 3 / 2,
>       autoPlay: true,
>       looping: true,
>     );
>   }
> 
> @override
>   void dispose() {
>     _controller.dispose();
>     _chewieController.dispose();
>     super.dispose(); //Super should be called at the very end of dispose
>   }
> 
> //Let me know if this doesn't solve your issue.
> ```

this doesn't worked for me

**Comment by cbenhagen** [comment]
Can you please provide a non-working example?

**Comment by Ashwanimvit16** [comment]
I was using a list view so i just have to add cacheExtent and it solved the problem for me

**Comment by cbenhagen** [comment]
Please feel free to reopen a new issue if you think there is something we can do in `Chewie` to improve this.

**Comment by MahdiPishguy** [comment]
I have the same problem!

**Comment by VictorUvarov** [comment]
Make sure that you check if the widget is still mounted before you use the videoController

**Comment by Am607** [comment]
i have the same promlem

**Comment by Johndavid437** [comment]
i have the same problem still....
Any one find the solution please help me.

My code : 

import 'package:better_player/better_player.dart';


import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:responsive_widgets/responsive_widgets.dart';

class videolsight extends StatefulWidget {
  final String courseid;
  videolsight({required this.courseid});

  @override
  _videolsightState createState() => _videolsightState();
}

class _videolsightState extends State<videolsight> {
  final CollectionReference _productRef = FirebaseFirestore.instance.collection("lsight");


  @override
  Widget build(BuildContext context) {
    ResponsiveWidgets.init(
      context,
      height: MediaQuery.of(context).size.height,
      width: MediaQuery.of(context).size.width,
      allowFontScaling: false,
    );
    return ResponsiveWidgets.builder(
      height: MediaQuery.of(context).size.height,
      width: MediaQuery.of(context).size.width,
      allowFontScaling: false,
      child: OrientationBuilder(
        builder: (context, orientation){
      if(orientation == Orientation.portrait){
        return Scaffold(
            body: Stack(
              children: [
                FutureBuilder<dynamic>(
                  future: _productRef.doc(widget.courseid).get(),
                  builder: (context, snapshot) {
                    if (snapshot.hasError) {
                      return Scaffold(
                        body: Center(
                          child: Text("Error : ${snapshot.error}"),
                        ),
                      );
                    }
                    if (snapshot.connectionState == ConnectionState.done) {

                      Map<String, dynamic> documentData = snapshot.data.data();

                      return Scaffold(

                        body: SingleChildScrollView(
                          child: Column(
                            children: [
                              Padding(
                                  padding: const EdgeInsets.only(top:20,),
                                  child: BetterPlayer.network(documentData["video"],

                                  )
                              ),


                              Padding(
                                padding:  const EdgeInsets.only(top: 25,),
                                child: Text("Class Name : ${documentData['name']}", style:  GoogleFonts.poppins(            fontSize: 20,
                                    fontWeight: FontWeight.w600
                                ),
                                  textAlign: TextAlign.left,
                                ),
                              ),


                            ],
                          ),
                        ),
                      );
                    }


                    return Scaffold(
                      body: Center(
                        child: CircularProgressIndicator(
                          color: Color(0xff005AA6),
                        ),
                      ),
                    );
                  },
                ),
                Padding(
                  padding: const EdgeInsets.only(top: 320,left: 10),
                  child: Text("More on this Course :",style: TextStyle(

                      fontWeight: FontWeight.w800,
                      fontSize: 16
                  ),

                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(top: 340),
                  child: FutureBuilder<QuerySnapshot>(
                    future: _productRef.orderBy('class',).get(),
                    builder: (context, snapshot) {
                      if (snapshot.hasError) {
                        return Scaffold(
                          body: Center(
                            child: Text("Error : ${snapshot.error}"),
                          ),
                        );
                      }
                      if (snapshot.connectionState == ConnectionState.done) {
                        return ListView(
                          children: snapshot.data!.docs.map((document) {
                            return GestureDetector(
                              onTap: () {
                                Navigator.pushReplacement(context, MaterialPageRoute(
                                    builder: (context) =>
                                        videolsight(courseid: document.id,)));

                              },
                              child: Container(
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(18.0),
                                  ),
                                  margin: EdgeInsets.symmetric(
                                    vertical: 1.0,
                                    horizontal: 4.0,
                                  ),
                                  child: Row(
                                    children: [
                                      Padding(
                                        padding: const EdgeInsets.all(8.0),
                                        child: Container(
                                          width: 90,
                                          height: 90,
                                          child: ClipRRect(
                                            borderRadius: BorderRadius.circular(12.0),
                                            child: SvgPicture.network(
                                              "${document['image']}",
                                              fit: BoxFit.cover,
                                              placeholderBuilder: (BuildContext context) => Scaffold(
                                                body: Center(
                                                  child: Container(
                                                      width: 50,
                                                      height: 50,

                                                      child: Image.asset("assets/load.gif",) ),
                                                ),
                                              ),

                                            ),
                                          ),
                                        ),
                                      ),
                                      Padding(
                                        padding: const EdgeInsets.all(8.0),
                                        child: Container(
                                          width: MediaQuery
                                              .of(context)
                                              .size
                                              .width*0.60,
                                          child: Text(
                                            document['name'] ?? "Course",
                                            style: TextStyle(
                                                fontWeight: FontWeight.w800,
                                                fontSize: 20
                                            ),),
                                        ),
                                      ),
                                    ],
                                  )
                              ),
                            );
                          },).toList(),
                        );
                      }
                      return Scaffold(
                        body: Center(
                          child: CircularProgressIndicator(color: Color(0xff005AA6)),
                        ),
                      );
                    },
                  ),
                ),
              ],
            )
        );}
      else{
        return Scaffold(
          body:  FutureBuilder<dynamic>(
            future: _productRef.doc(widget.courseid).get(),
            builder: (context, snapshot) {
              if (snapshot.hasError) {
                return Scaffold(
                  body: Center(
                    child: Text("Error : ${snapshot.error}"),
                  ),
                );
              }
              if (snapshot.connectionState == ConnectionState.done) {

                Map<String, dynamic> documentData = snapshot.data.data();

                return Scaffold(

                  body: SingleChildScrollView(
                    child: Column(
                      children: [
                        BetterPlayer.network(documentData["video"],
                          betterPlayerConfiguration: BetterPlayerConfiguration(
                            fullScreenByDefault: true,
                              controlsConfiguration: BetterPlayerControlsConfiguration(
                                fullscreenDisableIcon: Icons.cast,
                                fullscreenEnableIcon:  Icons.cast,
                              )
                          ),
                        ),





                      ],
                    ),
                  ),
                );
              }


              return Scaffold(
                body: Center(
                  child: CircularProgressIndicator(
                    color: Color(0xff005AA6),
                  ),
                ),
              );
            },
          ),
        );
      }
      }
      ),
    );
  }
}




Please help me with this . I'm struggling for days

**Comment by Nialixus** [comment]
Adding cache extent to the list still works to this day. You're a lifesaver, @js1972!
