### ISSUE TITLE
How to get aspect of each video?

### ISSUE THREAD

**Issue by VictorUvarov** [brianegan/chewie#174]
Is there a way to calculate the aspect ratio of an asset, network, or file video? I know that the VideoPlayerController class lets you use the aspect ratio value, but it always seems to be 1.0.

I want to do something like this:
```dart
if (videoURL != null)
  _videoPlayerController = VideoPlayerController.network(videoURL);
else
  _videoPlayerController = VideoPlayerController.file(videoFile);

chewieController = ChewieController(
  videoPlayerController: _videoPlayerController,
  aspectRatio: _videoPlayerController.value.aspectRatio, // always equals 1.0
);
```

**Comment by yanisalfian** [comment]
You should wrap ```Chewie``` inside FutureBuilder. Initialize the video controller inside the future and pass the aspect ratio ```_controller.value.aspectRatio``` to chewie controller.
 
This is my work around to get and set the aspect ratio.

```[dart]
  VideoPlayerController _controller;
  ChewieController _chewieController;
  Future<void> _future;
  String videoUrl = 'video url here'

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(videoUrl);
    _future = initVideoPlayer();
  }

  @override
  void dispose() {
    _controller.dispose();
    _chewieController.dispose();
    super.dispose();
  }

  Future<void> initVideoPlayer() async{
    await _controller.initialize();
    setState(() {
      _chewieController = ChewieController(
        videoPlayerController: _controller,
        aspectRatio: _controller.value.aspectRatio,
        autoPlay: true,
        looping: true,
        placeholder: buildPlaceholderImage()
      );
    });
  }

  buildPlaceholderImage(){
    return Center(
       child: CircularProgressIndicator(),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FutureBuilder(
        future: _future,
        builder: (context, snapshot){
            if(snapshot.connectionState == ConnectionState.waiting) return buildPlaceholderImage();

            return Center(
               child: Chewie(controller: _chewieController,),
             );
          },
      )
    );
  }
```

**Comment by VictorUvarov** [comment]
Thanks  I forgot to call `await _controller.initialize();`

**Comment by micsan13br** [comment]
The futurebuilder was key to correctly read the aspect ratio on iPad Air 2.
On Android Phones, Android Tablets and iPhone it just worked with the suggested method.

**Comment by micsan13br** [comment]
This should be reopened because it's still an issue.

This is my VideoPlayer class here:

`import 'package:flutter/material.dart';

import 'dart:io';

import 'package:chewie/chewie.dart';
import 'package:video_player/video_player.dart';

class MyVideoPlayer extends StatefulWidget {
  final String path;

  MyVideoPlayer({Key key, @required this.path}) : super(key: key);

  @override
  _MyVideoPlayerState createState() => new _MyVideoPlayerState();
}

class _MyVideoPlayerState extends State<MyVideoPlayer> {

  VideoPlayerController _videoPlayerController;
  ChewieController _chewieController;
  Future<void> _future;

  Future<void> initVideoPlayer() async {
    await _videoPlayerController.initialize();
    setState(() {
      print(_videoPlayerController.value.aspectRatio);
      _chewieController = ChewieController(
        videoPlayerController: _videoPlayerController,
        aspectRatio: _videoPlayerController.value.aspectRatio,
        autoPlay: false,
        looping: false,
      );
    });
  }

  @override
  void initState() {
    super.initState();
    // _controller = VideoPlayerController.network('https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4');
    _videoPlayerController = VideoPlayerController.file(File(widget.path));
    _future = initVideoPlayer();
  }

  @override
  Widget build(BuildContext context) {
    return new FutureBuilder(
      future: _future,
      builder: (context, snapshot) {
        return new Center(
          child: _videoPlayerController.value.initialized
          ? AspectRatio(
            aspectRatio: _videoPlayerController.value.aspectRatio,
            child: Chewie(
              controller: _chewieController,
            ),
          )
          : new CircularProgressIndicator(),
        );
      }
    );
  }
  
  @override
  void dispose() {
    _videoPlayerController.dispose();
    _chewieController.dispose();
    super.dispose();
  }
}
`

which gets instantiated by passing the video file path from the app storage folder.
`MyVideoPlayer videoPlayer = new MyVideoPlayer(path: assetFilePath);`

**Comment by nono1008** [comment]
> This should be reopened because it's still an issue.
> 
> This is my VideoPlayer class here:
> 
> ```
> import 'package:flutter/material.dart';
> import 'dart:io';
> import 'package:chewie/chewie.dart';
> import 'package:video_player/video_player.dart';
> 
> class MyVideoPlayer extends StatefulWidget {
>   final String path;
> 
>   MyVideoPlayer({Key key, @required this.path}) : super(key: key);
> 
>   @override
>   _MyVideoPlayerState createState() => new _MyVideoPlayerState();
> }
> 
> class _MyVideoPlayerState extends State<MyVideoPlayer> {
> 
>   VideoPlayerController _videoPlayerController;
>   ChewieController _chewieController;
>   Future<void> _future;
> 
>   Future<void> initVideoPlayer() async {
>     await _videoPlayerController.initialize();
>     setState(() {
>       print(_videoPlayerController.value.aspectRatio);
>       _chewieController = ChewieController(
>         videoPlayerController: _videoPlayerController,
>         aspectRatio: _videoPlayerController.value.aspectRatio,
>         autoPlay: false,
>         looping: false,
>       );
>     });
>   }
> 
>   @override
>   void initState() {
>     super.initState();
>     // _controller = VideoPlayerController.network('https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4');
>     _videoPlayerController = VideoPlayerController.file(File(widget.path));
>     _future = initVideoPlayer();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return new FutureBuilder(
>       future: _future,
>       builder: (context, snapshot) {
>         return new Center(
>           child: _videoPlayerController.value.initialized
>           ? AspectRatio(
>             aspectRatio: _videoPlayerController.value.aspectRatio,
>             child: Chewie(
>               controller: _chewieController,
>             ),
>           )
>           : new CircularProgressIndicator(),
>         );
>       }
>     );
>   }
>   
>   @override
>   void dispose() {
>     _videoPlayerController.dispose();
>     _chewieController.dispose();
>     super.dispose();
>   }
> }
> ```
> 
> which gets instantiated by passing the video file path from the app storage folder.
> `MyVideoPlayer videoPlayer = new MyVideoPlayer(path: assetFilePath);`

your class works in my test app, and what's the issue?

**Comment by Arundas-v93** [comment]
Same Code but got these problems.

`PlatformException (PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4, null))`

**Comment by VictorUvarov** [comment]
Video player only supports https

**Comment by dantheman213** [comment]
Why was this ticket closed? Is there now a trivial method to get the aspect ratio of a video or to better yet have it automatically set without having to manually set it for Chewie?

**Comment by shubhamgarg1** [comment]
For me, things work fine, if I don't set Chewie controller's aspect ratio and only use the aspect ratio for the original video player controller.

i.e. instead of
`_chewieController = ChewieController(
        videoPlayerController: _videoPlayerController,
        aspectRatio: _videoPlayerController.value.aspectRatio,
        autoPlay: false,
        looping: false,
      );`

I use this:

`_chewieController = ChewieController(
        videoPlayerController: _videoPlayerController,
        autoPlay: false,
        looping: false,
      );`
