### ISSUE TITLE
No image on samsung tab 10

### ISSUE THREAD

**Issue by hamidabdulmalik** [brianegan/chewie#18]
No image show on Samsung tab 10 214 edition, just audio. works well on emulator.

**Comment by brianegan** [comment]
Thanks for writing in! Could you please try using the raw video_player plugin and seeing if that works? If it fails, we probably need to file a bug against that project (Chewie only provides a nice UI on top of the video_player plugin).

**Comment by brianegan** [comment]
Hi @hamidabdulmalik -- any follow up on this one? Chewie could be at fault here, but so could the video_player package. Unfortunately, I don't have a Samsung Tab 10 to try this on myself, so any help would be appreciated.

**Comment by brianegan** [comment]
Hi @hamidabdulmalik -- any follow up on this one? Chewie could be at fault here, but so could the video_player package. Unfortunately, I don't have a Samsung Tab 10 to try this on myself, so any help would be appreciated.

**Comment by hamidabdulmalik** [comment]
Oh yes, actually the issue was not from Chewie as I later found out. It is from the flutter platform itself. I had to switch to master and everything is working perfectly now. Thanks for following up with me.

**Comment by hamidabdulmalik** [comment]
So I guess this is closed.
