### ISSUE TITLE
Videoplayer preview thumbnail

### ISSUE THREAD

**Issue by jesuschrist33** [brianegan/chewie#182]
Hey guys, could you give me an idea if the chewie player has an out of the box option to give it a first background preview image? If not what is the best way to deal with? Thanks

**Comment by d-apps** [comment]
If you use autoInitialize: true, inside ChewieController the thumbnail will appear.

**Comment by pcegarra** [comment]
What about a list of videos? we cant auto play all

**Comment by lifenautjoe** [comment]
@d-apps , I've tried autoinitialize: true and no thumbnail appears, only a progress indicator in the center.

**Comment by cbenhagen** [comment]
You can set the `placeholder` property to any widget you would like to be shown before the video is initialized or played. Please feel to reopen or comment if this is not working for you.

**Comment by pcegarra** [comment]
@cbenhagen but using the placeholder the progress bar is above it

**Comment by Sub6Resources** [comment]
@cbenhagen The `placeholder` property is only used for before the video is initialized. In my case, the first few frames of my video are black, so I'd like to show a thumbnail after the video is initialized, but before it is played. I think this is a pretty common case.

**Comment by tudor07** [comment]
@cbenhagen can you re-open? Thumbnail on iOS still does not work
