### ISSUE TITLE
暂停自动播放的问题

### ISSUE THREAD

**Issue by shuaiwang007** [brianegan/chewie#183]
autoPlay: false
播放器一直在加载状态
![11564973310_ pic_hd](https://user-images.githubusercontent.com/12870683/62435394-97a57780-b76e-11e9-8ec0-283ad62befb3.jpg)

**Comment by shuaiwang007** [comment]
只有缓冲完才能播放？

**Comment by lalaMiao** [comment]
iOS上体验极差,  我找遍了 发现 ijkplayer 那个可以, 不过还是有点小问题

**Comment by cbenhagen** [comment]
Can't reproduce the issue. Can you please provide a non-working example?

Google translated:
无法重现这个问题。 你能提供一个非工作的例子吗？

**Comment by Darren-chenchen** [comment]
autoPlay: false  播放器一直在加载状态  ,我的也是
videoPlayerController = VideoPlayerController.network(
        'http://vd2.bdstatic.com/mda-jj10rp267hagatih/sc/mda-jj10rp267hagatih.mp4');
    chewieController = ChewieController(
      videoPlayerController: videoPlayerController,
      aspectRatio: 1,
      autoPlay: false
    );

**Comment by Darren-chenchen** [comment]
好像是这个方法没有初始化  await videoPlayerController.initialize();
