### ISSUE TITLE
After ios is packaged, I can't open it.   But android can, ioscan't

### ISSUE THREAD

**Issue by jahnli** [brianegan/chewie#186]
![75fdf90adc6274487c5d63733239a97](https://user-images.githubusercontent.com/20943608/63395477-75f6f200-c3f6-11e9-9d32-ab0086051fe9.jpg)

When I tried to open video with it, I got this error,    But android can, ioscan't

**Comment by cbenhagen** [comment]
Can you please provide a minimal sample? Could it be that you are trying to play a video which iOS does not support?

**Comment by cbenhagen** [comment]
Without further info we can't do anything about this issue. I am therefore closing it. Please add details if you think this should be reopened.
