### ISSUE TITLE
Video player controls outside Video container.

### ISSUE THREAD

**Issue by lifenautjoe** [brianegan/chewie#190]
I'm trying to build something like the image below, when expanded displays the controllers on the bottom of the screen, which is more intuitive. 

Is there a possibility to do this with Chewie?

Thanks!

![IMG_7BF8B51D0042-1](https://user-images.githubusercontent.com/12737509/64127792-7b1f4e00-cdb3-11e9-93fa-361c90de4a23.jpeg)

**Comment by cbenhagen** [comment]
This is not possible currently and I am not sure if we should support it. But if you want to create this I would recommend to use a custom fork of chewie and start by removing this AspectRatio widget: https://github.com/brianegan/chewie/blob/master/lib/src/player_with_controls.dart#L20

**Comment by lifenautjoe** [comment]
Thanks for the pointer Ben! 

I've looked across several apps and it's a common pattern. The only app I could find where it's not, it's YouTube.

Here's 2 to show this

LinkedIn

![linkedin](https://user-images.githubusercontent.com/12737509/64133516-e7f80f80-cdd6-11e9-8e97-0d18c2651d20.gif)

9Gag

![9gag](https://user-images.githubusercontent.com/12737509/64133528-f80fef00-cdd6-11e9-9f5e-ac4fbc7be685.gif)


I'll give creating something similar a try tomorrow, keep you posted :-)

**Comment by lifenautjoe** [comment]
Worked great. Found another issue though. Will open a new one :-)
