### ISSUE TITLE
Hide controlers on autoplay

### ISSUE THREAD

**Issue by lifenautjoe** [brianegan/chewie#191]
Is there a way to prevent the controllers from flashing when autoplaying?

As shown below, when a video is autoplayed, the overlay appears with the controllers for a couple of seconds before dissapearing.

![demo](https://user-images.githubusercontent.com/12737509/64130426-71511700-cdc2-11e9-8e60-6d33da64cb83.gif)

Thanks for the great work Brian!

**Comment by cbenhagen** [comment]
Added a pull request for this https://github.com/brianegan/chewie/pull/192

**Comment by lifenautjoe** [comment]
Awesome stuff Ben! Thank you.

Hoping Brian has some time to look into this :-)

**Comment by lifenautjoe** [comment]
Hey Ben, just another quick question, perhaps you know it top of your head. Do you know how could I prevent the video player being rebuilt over and over again as scrolling down and up?

Thanks!

**Comment by lifenautjoe** [comment]
It all works Ben! Thank you!
I've forked the repo and merged your PR there, we have custom controllers, so had to integrate your changes there too.

![image](https://user-images.githubusercontent.com/12737509/64173984-c8a1c680-ce58-11e9-97d9-2baab26f6ad3.png)
