### ISSUE TITLE
Video playback status and process are out of sync

### ISSUE THREAD

**Issue by RainSnowSnow** [brianegan/chewie#193]
@brianegan 
![image](https://user-images.githubusercontent.com/23568119/64223814-d9f5dc00-cf07-11e9-8f0e-77802e5e82f0.png)
![image](https://user-images.githubusercontent.com/23568119/64223825-e5e19e00-cf07-11e9-996c-b6e42e99f4ec.png)
存在的问题：
视频已经播放结束，但是状态isPlaying还是true的状态

(google translate)
Problems:
The video has ended, but the state isPlaying is still true.

**Comment by cbenhagen** [comment]
This seems to be an issue with the `video_player` plugin. Chewie only provides the GUI on top of it. Please open an issue at https://github.com/flutter/flutter/issues with the output of `flutter doctor -v` and a full example demonstrating the issue.
