### ISSUE TITLE
Question regarding custom controls usage

### ISSUE THREAD

**Issue by freitzzz** [brianegan/chewie#197]
Hi everyone.

Shouldn't Material & Cupertino control widgets expose some of their control properties such as `_hideStuff` and `_hideTimer`? I dont get why Chewie allows developers to use "custom" controls when these aren't custom at all.

Cheers,
freitzzz

**Comment by cbenhagen** [comment]
They way this currently works is that you create your own implementation based on `MaterialControls` or `CupertinoControls`. From there you can expose whatever you need. But if you think more should be exposed in the provided control widgets, please feel free to open a PR. I'd be happy to discuss concrete suggestions.

**Comment by freitzzz** [comment]
Thank you for the response @cbenhagen 
As for now this issue can be closed
