### ISSUE TITLE
Placeholder image for audio file

### ISSUE THREAD

**Issue by loicgeek** [brianegan/chewie#198]
Please is there a way to show image when we load an audio file?

**Comment by xal** [comment]
I think it is better to fully remove video texture and only display audio controls. In this case, the library can be used as a good audio player too, for example, to embed audio in chat apps

**Comment by Sub6Resources** [comment]
@xal I've forked this library and modified it to only display audio controls. See https://github.com/Sub6Resources/chewie_audio

**Comment by loicgeek** [comment]
Ok thanks a lot

**Comment by cbenhagen** [comment]
I am closing this, as playing audio files is out of scope for this plugin.
