### ISSUE TITLE
not working video when play m3u and m3u8 url iptv 

### ISSUE THREAD

**Issue by Ghrib-Ramadhan** [brianegan/chewie#199]
hi guys 
i have problem when play m3u and m3u8 url iptv streamig not working and not show anythink

**Comment by VivekAgar** [comment]
Same here, I was trying, to play a m3U8 stream it just showed first frame and stucked.

**Comment by shabbirh** [comment]
I have the same problem, only on iOS

**Comment by jorgeperez777** [comment]
Can you fix the problem?

**Comment by hadiarakos** [comment]
Hello. Same problem. I try also with video_player and I had same results..

**Comment by cbenhagen** [comment]
Thank you for reporting this. Chewie is just a GUI layer on top of the video_player plugin. Please check the open [issues](https://github.com/flutter/flutter/search?q=m3u8&unscoped_q=m3u8&type=Issues) or add a new one if you are sure your case is different.

**Comment by WingCH** [comment]
I found a temporary solution in iOS.

https://github.com/flutter/flutter/issues/48670#issuecomment-599192285
