### ISSUE TITLE
Better Cupertino Icons

### ISSUE THREAD

**Issue by brianegan** [brianegan/chewie#2]
Looks like the Flutter team has some Cupertino icons in a font, but does not expose all of them yet. Watch for updates to the Flutter repo and use the better icons when available.

**Comment by cbenhagen** [comment]
Which Icons do you have in mind?

**Comment by brianegan** [comment]
Oldie but goodie -- was hoping to use the CupertinoIcons packaged with Flutter. The problem: When I last checked, the font the ship has a bunch of icons, but the class itself only exposes a few of those icons.

**Comment by cbenhagen** [comment]
Relevant flutter issue: https://github.com/flutter/flutter/issues/16102. But it seems there are not all icons we would need when you look at the map: https://raw.githubusercontent.com/flutter/cupertino_icons/master/map.png
