### ISSUE TITLE
not competitive with video_player version

### ISSUE THREAD

**Issue by fukemy** [brianegan/chewie#20]
Hello.
Your lib not working in newest video_player version, plz update it. Thanks you
Because chewie 0.3.0 depends on video_player ^0.2.0 and no versions of chewie match >0.3.0 <0.4.0, chewie ^0.3.0 requires video_player ^0.2.0.
So, because icamerasolution depends on both video_player ^0.5.3 and chewie ^0.3.0, version solving failed.
pub get failed (1)

**Comment by brianegan** [comment]
Thanks, I'll patch that up!

**Comment by brianegan** [comment]
Fixed and deployed as version `chewie: >=5.0.0 <6.0.0`
