### ISSUE TITLE
Method not found: 'MouseRegion'

### ISSUE THREAD

**Issue by ruelluna** [brianegan/chewie#200]
### pubscpec.yaml
```
   chewie: ^0.9.8
   video_player: ^0.10.2+1
```

`Error: The method 'MouseRegion' isn't defined for the class '_CupertinoControlsState'.`

**Comment by cbenhagen** [comment]
Looks like you need to update your flutter version to the latest stable version.

**Comment by VictorUvarov** [comment]
To remove this issue, I had to reinstall flutter.

**Comment by ezra126** [comment]
i tried to update the version but it doesn't work

**Comment by cbenhagen** [comment]
@ezra126 what did you try to update? `flutter upgrade` should be enough. `MouseRegion` is released in the stable channel. Can you show me the output of `flutter doctor`?

**Comment by jsgalarraga** [comment]
For me upgrading flutter fixed the problem. Thanks!

**Comment by probuse** [comment]
upgrading my flutter package fixed my problem

**Comment by sur950** [comment]
Do we have any other alternatives(Other than flutter upgrade) where we get solution for this problem?
