### ISSUE TITLE
White background and only sound plays

### ISSUE THREAD

**Issue by klaszlo8207** [brianegan/chewie#202]
I am using with this package: https://pub.dev/packages/overlay_container

I can hear only voices, but not any picture :(

Android 9.0 
Huawei Mate 20 Pro

**Comment by klaszlo8207** [comment]
Android 9.0 
Mate 20 Pro

**Comment by ixzk** [comment]
same problem

**Comment by cbenhagen** [comment]
@klaszlo8207 Please update https://github.com/flutter/flutter/issues/40573 with more information.
