### ISSUE TITLE
A ChewieController was used after being disposed.

### ISSUE THREAD

**Issue by klaszlo8207** [brianegan/chewie#203]
My scenario:

0, Firstly I get 3 video urls from a firestore field with an async call.  
1, I created 3 videoControllers and load it via:

_videoPlayerControllers[index] = VideoPlayerController.network(videos[index]);

After that

_chewieController = ChewieController(
                          videoPlayerController: _videoPlayerControllers[0],
                          aspectRatio: 3 / 2,
                          autoPlay: true,
                          looping: false,
                        );

2, So I don't want to play the videos with Chewie for the first time. 
I have a PageView and 3 pictures with the video's thumb pix.
When you click on any thumb I need to play that video with chewie within an overlay.

3,
The second time I made a .dispose (I just copy and pasted from the example source) I get a:

A ChewieController was used after being disposed. (and a red screen, lot of error)

How to fix that?

When the exception was thrown, this was the stack: 
      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:105:9)
      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:111:6)
      ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:141:12)
      ChewieState.initState (package:myapp/_video/chewie_player.dart:46:23)
      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)

WEIRD THING IS: I can hear the video, but only see the red screen with yellow "A ChewieController was used after being disposed."

**Comment by klaszlo8207** [comment]
The best thing is that in the example this is working like a charm (but it plays immediatelly), but in my overlay I get a lot of errors.

**Comment by klaszlo8207** [comment]
More errors:

When I set: autoPlay: false,

than I see a loading indicator and nothing else... When I click on the play button it not working. Maybe this is a BUG as well.

**Comment by klaszlo8207** [comment]
When I don't call: chewieController.dispose(); after I change the video url, I can hear the video 2 sounds but I don't see the video 1 images, only the video 2 but frozen.

**Comment by VictorUvarov** [comment]
I see you are using the provider package. Provider by default disposes of a widget for you. You might have an extra dispose method.

**Comment by klaszlo8207** [comment]
I ended up to use 3 chewieController with 3 videoControllers. It is now working, but not the best solution

**Comment by teekamsuthar** [comment]
> I ended up to use 3 chewieController with 3 videoControllers. It is now working, but not the best solution

Hey, I'm having the same issue. Could you please provide me with your solution? if you still have access to code. Thanks.

**Comment by viethoang2603** [comment]
> Hey, I'm having the same issue. Could you please provide me with your solution? if you still have access to code. Thanks.

Did you deal this issue? I'm facing the same issue.

**Comment by teekamsuthar** [comment]
> > Hey, I'm having the same issue. Could you please provide me with your solution? if you still have access to code. Thanks.
> 
> Did you deal this issue? I'm facing the same issue.

Sorry but I left the project after I realised flutter isn't a good choice for it. At least in my case! I was having a lot of issues so used native development instead.

**Comment by rohitsahu1920** [comment]
> > Hey, I'm having the same issue. Could you please provide me with your solution? if you still have access to code. Thanks.
> 
> Did you deal this issue? I'm facing the same issue.

Did you deal this issue? I'm facing the same issue.
