### ISSUE TITLE
need an onInitialized() for autoInitialize: true

### ISSUE THREAD

**Issue by aytunch** [brianegan/chewie#209]
Right now I have `autoInitialize: true` and Chewie shows the first frame of the video as expected however I dont like the transition since the first frame image pops out suddenly from a black screen. So I wrapped `Chewie()` inside of an `AnimatedOpacity()` but I dont have a callback to set the `_opacity = 1.0` for a nice fade transition. I tried doing this with `_chewieController.videoPlayerController.value.initilized` inside of an `FutureBuilder` but nothing changed. I guess `_chewieController.videoPlayerController.initialized`does NOT mean first frame is laid out on the screen.

Can we have a callback which tells the user that Chewie is intialized and laid the first frame on the screen?

**Comment by aytunch** [comment]
I also opened up a SO question: https://stackoverflow.com/questions/58149835/flutter-package-chewie-how-to-know-video-controller-laid-the-first-frame-onto-t

**Comment by cbenhagen** [comment]
You can use:
```dart
_videoPlayerController.addListener(() {
  if (_videoPlayerController.value.initialized) {
    // do something here
  }
});
```
