### ISSUE TITLE
如何切换视频资源，比如播放完第一集，自动播放第二集。

### ISSUE THREAD

**Issue by yslings** [brianegan/chewie#213]
如何切换视频资源，比如播放完第一集，自动播放第二集。

(google translate)
How to switch video resources, such as automatically playing the second episode after playing the first episode.

**Comment by cbenhagen** [comment]
You can replace the ChewieController with a new one where you set another VideoPlayerController:
https://github.com/brianegan/chewie/blob/master/example/lib/main.dart#L117-L129
