### ISSUE TITLE
Vimeo

### ISSUE THREAD

**Issue by sukhkmr19** [brianegan/chewie#220]
Not playing Vimeo links...

**Comment by cfl777** [comment]
Yes it is - works fine. Make sure the vimeo link you are using the "video file links" with a pro account

**Comment by cbenhagen** [comment]
Closing this as it seems to be resolved. If not, please be aware that `Chewie` is only a GUI layer on top of the official `video_player` plugin. I don't think there is anything for us to do here so I am closing this. Please open an issue for the `video_player` plugin on https://github.com/flutter/flutter/issues with an example application an the output of `flutter doctor -v`.

**Comment by klaszlo8207** [comment]
What is the correct url for VIMEO?

Is it good? https://player.vimeo.com/video/4084irjijojo
