### ISSUE TITLE
Plugin not supported user-agent in some video 

### ISSUE THREAD

**Issue by Ghrib-Ramadhan** [brianegan/chewie#221]
I have some link url m3u stream but this links play using user-agent, it's possible add user-agent to play this link.
Please I need this option because I have links url support user-agent

**Comment by cbenhagen** [comment]
`Chewie` is only a GUI layer on top of the official `video_player` plugin. I don't think there is anything for us to do here so I am closing this. Please open an issue for the `video_player` plugin on https://github.com/flutter/flutter/issues with an example application an the output of `flutter doctor -v`.
