### ISSUE TITLE
Possible to start later than 0

### ISSUE THREAD

**Issue by Reached** [brianegan/chewie#227]
Hi there,

Great library! 

Is it possible offset start to a later point in the video once it's loaded? E.g. 5 minutes in?

Sort of this:  `seekToTime(seconds)`

Hope it makes sense, best regards, Casper

**Comment by Crispy** [comment]
ChewieController already has this ability.
```
`class ChewieController extends ChangeNotifier {
  ChewieController({

```
....

    this.startAt,

...

```
  /// Start video at a certain position
  final Duration startAt;
`
```

**Comment by cbenhagen** [comment]
Thanks @Crispy !

**Comment by Reached** [comment]
Thanks @Crispy !! :)
