### ISSUE TITLE
Launch video in fullscreen through a custom button.

### ISSUE THREAD

**Issue by BlissPB** [brianegan/chewie#23]
Hello,
I wanted to hide the video controls and alternatively launch the video in fullscreen when the user clicks on a specific button. I know that you can hide the controls through showControls attribute but I was wondering if there was anything to change the video to fullscreen. I do not think that the video_player plugin has anything of such functionality either although it does have a setVolume property which is missing in chewie. I was hoping if you knew anything about setting the video to fullscreen without relying on the video controls or could create such functionality.
Thank You.

**Comment by brianegan** [comment]
Hey hey :) Hrm, I might need to think about the best way to implement this functionality. 

I might need to implement something like a `ChewieController` that would allow you to drive the Chewie player from outside the player itself. This might actually be helpful for a few different cases that others are asking about!

I'll try to find some time this week to look into it.

**Comment by BlissPB** [comment]
That sounds great! Thank you very much. I do not have much experience with dart and flutter, so your project already helps a ton.

**Comment by robin7331** [comment]
Any updates on this?

**Comment by cbenhagen** [comment]
@robin7331 I will start the implementation of a `ChewieController` today. Will link the WIP PR as soon as I made some progress.

**Comment by cbenhagen** [comment]
@BlissPB and @robin7331 please check out my branch from #99.
