### ISSUE TITLE
Controls invisible

### ISSUE THREAD

**Issue by cc123** [brianegan/chewie#231]
I have a weird problem - Chewie is working just fine, but the controls aren't showing. Here's an example (ignore the other colors, I'm using those to see where Chewie begins and ends within the Container/Box Decoration I've placed it in.

Chewie works just fine - since I know where the controls are, even though they are invisible/transparent, I can click in that area, and they show up. This includes playing, stopping, full-screen - it all works just great, but I just can't see the play/pause/full screen controls (even though they are there and working.) Here's a pic:

![1](https://user-images.githubusercontent.com/867228/68500691-8eb6bd00-0219-11ea-852a-7f5dd174e170.png)

Any ideas would be great.

**Comment by cc123** [comment]
In trying to diagnose this weirdness in the two Chewie Example apps in the repo. You'll see they do the following in their build methods:

return MaterialApp(
      title: "video",
      theme: ThemeData.light().copyWith(
        platform: _platform ?? Theme.of(context).platform,
      ),

etc...

This displays and functions perfectly. However, since I'm jumping from another page in my app, I don't really need another MaterialApp or ThemeData - so if I simplify this build method and only return the Scaffold with everything else in it, then the invisible control situation appears again (but everything functions like normal), so I'm back to where I started, but this time using the provided example apps.

Since I'm trying to embed Chewie in-line in another page in my app, it would be nice to know what to set so that the Chewie controls always appear.

**Comment by cbenhagen** [comment]
If you want to change the theme of parts of your widget tree, just wrap it it in a `Theme` widget. Please check https://flutter.dev/docs/cookbook/design/themes for more info.

I am closing this as I don't think there is anything for us to do here.
