### ISSUE TITLE
Play from memory video

### ISSUE THREAD

**Issue by yeganaaa** [brianegan/chewie#241]
now I'm making a movies app using flutter,
I want to encode/decode movie segments in memory using my own algorithm and play it with video_player plugin, but I can't find like 'VideoPlayerController.memory' method.

now video_player supported only play from asset, local file, network,
it's not provide play video from memory source (UInt8List, List...)
I have some Android kotlin development experience and server side development with kotlin etc, but I have no any IOS/macOS development experience with obj-c/Swift and I have no any apple development environment (macOS, Ios devices),
can possible to provide play movie from memory source (e.g. UInt8List) as will?
thank you.

**Comment by cbenhagen** [comment]
`Chewie` is only a GUI layer on top of the official `video_player` plugin. I don't think there is anything for us to do here so I am closing this. Please open a feature request for the `video_player` plugin on https://github.com/flutter/flutter/issues.
