### ISSUE TITLE
The player cannot release the video resource after using full screen.

### ISSUE THREAD

**Issue by chengaddone** [brianegan/chewie#242]
After using the full screen function of the player, exit the full screen and then exit the current page. The current video does not stop playing, and the resources of that video seem to be unable to be released.

**Comment by CoderMonkie** [comment]
maybe Y R using it in a wrong way~
try pause it first .
---

I have a demo and that may help..

**Comment by chengaddone** [comment]
Yes, this problem is not the cause of the player, I found my mistake, I added the control components outside the player and then did not release them inside the player, I put the controller in the player to solve this problem, but then a new problem was discovered: when you press the phone's back button in Android full screen mode, the page will turn into a horizontal screen. Finally, thank you very much for this player, it helped me a lot.

**Comment by chengaddone** [comment]
When the entire project has only a player page, press the back key to successfully exit the full screen. When jumping from other pages to the video playback page and then pressing the mobile phone's back key to exit the full screen, the above-mentioned horizontal screen problem will occur

**Comment by chengaddone** [comment]
The problem seems to be solved. When jumping from other pages to the player page, the player page does not need to use MarteryApp.

**Comment by shreyas17** [comment]
can you please provide the code snippet?

**Comment by cbenhagen** [comment]
I am closing this as I don't think there is anything to do from our side.
