### ISSUE TITLE
Playing http streams does not work

### ISSUE THREAD

**Issue by csongorkeller** [brianegan/chewie#245]
Hi,
I've tried to play http streams and I can only play Https m3u8 files. How can I use Chewie to play them? Thanks a lot

**Comment by FadiSweden** [comment]
in AndroidManifest.xml add this `android:usesCleartextTraffic="true"` to application

**Comment by cbenhagen** [comment]
`Chewie` is only a GUI layer on top of the official `video_player` plugin. I don't think there is anything for us to do here so I am closing this.
