### ISSUE TITLE
About video preloading

### ISSUE THREAD

**Issue by a642815311** [brianegan/chewie#246]
I have a situation where a white exclamation point sometimes appears when preloading a video. I'm not sure if this is a problem with the video source. Can you help me?

```dart
Chewie(
    controller: ChewieController(
        videoPlayerController: bloc.videoPlayerController1,
        autoInitialize: false,
        aspectRatio: MediaQuery.of(context).size.width /
            MediaQuery.of(context).size.height,
        autoPlay: false,
        looping: false,
        showControls: false,
    ),
)
```

**Comment by cbenhagen** [comment]
This is most likely a problem with your source yes. As `Chewie` is only a GUI layer on top of the official `video_player` plugin, may I ask you to verify if you can play the source with that plugin? If this is indeed a problem with `Chewie`, please open a new issue with a full example and the output of `flutter doctor -v`.
