### ISSUE TITLE
VideoPlayer text color is now adjustable

### ISSUE THREAD

**Issue by Milansu** [brianegan/chewie#248]
@brianegan Current videoplayer uses TextTheme(body1) as its default color.
I've changed it to be manually adjustable 
Example:

```dart
  _chewieController = ChewieController(
      videoPlayerController: widget.videoPlayerController,
      textPlayerColor: Colors.white,
);
```
Forked repo: `https://github.com/Milansu/chewie`

**Comment by cbenhagen** [comment]
I don't think this is the right approach. If you want to change the color of the text you can do this globally in the theme or like this:
```dart
DefaultTextStyle(
  style: TextStyle(color: Colors.pink),
  child: Chewie(
    controller: _chewieController,
  ),
)
```

This does not currently work with the `CupertinoControls` though.

**Comment by Ahmadre** [comment]
I can confirm what @cbenhagen already said.

I want to add to it: use ThemeData.copyWith() to add custom themes for a specific part of Flutter code :).

Closing this for now. Feel free to reopen.
