### ISSUE TITLE
Video doesn't play in full screen

### ISSUE THREAD

**Issue by superciccio** [brianegan/chewie#25]
Hi,
I have an issue when I click the icon to play in full screen.
It shows a play button but it doesn't work and when I click back I can see the error on the screen and console.

I'm copying the erro in case I'm missing something

`I/ViewRootImpl(21950): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(21950): ViewRoot's Touch Event : ACTION_UP
E/flutter (21950): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (21950): A VideoPlayerController was used after being disposed.
E/flutter (21950): Once you have called dispose() on a VideoPlayerController, it can no longer be used.
E/flutter (21950): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:61:9)
E/flutter (21950): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:67:6)
E/flutter (21950): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:155:12)
E/flutter (21950): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:217:5)
E/flutter (21950): #4      VideoPlayerController.play (package:video_player/video_player.dart:223:5)
E/flutter (21950): <asynchronous suspension>
E/flutter (21950): #5      _MaterialControlsState._playPause.<anonymous closure> (package:chewie/src/material_controls.dart:288:29)
E/flutter (21950): #6      State.setState (package:flutter/src/widgets/framework.dart:1125:30)
E/flutter (21950): #7      _MaterialControlsState._playPause (package:chewie/src/material_controls.dart:275:5)
E/flutter (21950): #8      _MaterialControlsState._buildHitArea.<anonymous closure> (package:chewie/src/material_controls.dart:122:17)
E/flutter (21950): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (21950): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (21950): #11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94:7)
E/flutter (21950): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (21950): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (21950): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (21950): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter (21950): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (21950): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (21950): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (21950): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (21950): #20     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (21950): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
`

Regards

**Comment by brianegan** [comment]
Thanks, we've got a fix in place for this one! Will publish soon.

**Comment by superciccio** [comment]
Hi,
I've upgraded to the latest version still same issue.
