### ISSUE TITLE
Could not get unknown property 'android' for project ':screen' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by Ian0903** [brianegan/chewie#250]
Reported this error when I built this project：Could not get unknown property 'android' for project ':screen' of type org.gradle.api.Project.

**Comment by cbenhagen** [comment]
Chewie is only a GUI layer on top of the official `video_player` plugin and does not contain any android code. Older versions of chewie used the `screen` plugin. Please try to upgrade your dependencies, run `flutter clean` and `flutter upgrade` and if you still can reproduce the issue report a new issue on the flutter repository.

I am closing this issue as I don't think there is anything we can do from our side. Please comment if you think there is really something wrong with `chewie`.
