### ISSUE TITLE
Aspect Ratio - Which one?

### ISSUE THREAD

**Issue by danielgchap** [brianegan/chewie#257]
Hi there,

it seems that the aspect ratio you use in the ChewieController never seems to be the right one. 
If you use 3/2 like the example shows, videos that are wide, look great. But if you use one from the iPhone gallery, that was done in portrait for example, it is stretched out.

I've also passed _controller.value.aspectRatio into the videoPlayerController parameter of the ChewieController and that doesn't work either. 

I just have the Chewie widget contained in a stack widget. 

Thoughts?

Thanks!

**Comment by vanth0me** [comment]
Either know the width and height and divide them. Or add a listener on the controller. Aspect ratio is 1 until the video is loaded/playing. I ran into the same problem.

**Comment by cbenhagen** [comment]
You can add a listener to the VideoPlayerController and get the aspect ratio when it is available.

**Comment by cbenhagen** [comment]
You can do it like here:
https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/example/lib/main.dart#L324-L368

I have just created a PR which contains those changes. Please give it a try:
https://github.com/brianegan/chewie/pull/260

**Comment by Ahmadre** [comment]
like @cbenhagen already mentioned: you have to fully initialize your `VideoPlayerController` from `video_player` before you give chewie the controller.

**Comment by danielgchap** [comment]
> like @cbenhagen already mentioned: you have to fully initialize your `VideoPlayerController` from `video_player` before you give chewie the controller.

THIS. This is the answer. I tried it last night before you commented this and it worked. You're a godsend Ahmadre. Thanks!
