### ISSUE TITLE
Is there a callback for the current position / play time?

### ISSUE THREAD

**Issue by tamoyal** [brianegan/chewie#259]
I'd like to maintain my own progress UI and just need to hook into some tick event that tells me the current play time. Does that exist?

**Comment by cbenhagen** [comment]
You can use `addListener()` of your  `VideoPlayerController`.

**Comment by tamoyal** [comment]
@cbenhagen Thank you for the fast response! I should have mentioned that I tried to add a listener and the callback was never invoked. Is there some way that could silently fail? Any pointers for debugging that?

**Comment by tamoyal** [comment]
@cbenhagen Sorry I was adding the listener to the `ChewieController` which does nothing. It seems to work for the `VideoPlayerController` as you suggested
