### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by Jackcui68** [brianegan/chewie#263]
setState() called after dispose(): _CupertinoControlsState#37839(lifecycle state: defunct, not mounted)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (35) Exception caught by foundation library ═══════════════════════════════════════════════
setState() called after dispose(): _CupertinoControlsState#c4362(lifecycle state: defunct, not mounted)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (36) Exception caught by foundation library ═══════════════════════════════════════════════
setState() called after dispose(): _CupertinoControlsState#c4362(lifecycle state: defunct, not mounted)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (37) Exception caught by foundation library ═══════════════════════════════════════════════
setState() called after dispose(): _CupertinoControlsState#c4362(lifecycle state: defunct, not mounted)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (38) Exception caught by foundation library ═══════════════════════════════════════════════
setState() called after dispose(): _CupertinoControlsState#c4362(lifecycle state: defunct, not mounted)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (39) Exception caught by foundation library ═══════════════════════════════════════════════
setState() called after dispose(): _CupertinoControlsState#37839(lifecycle state: defunct, not mounted)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (40) Exception caught by foundation library ═══════════════════════════════════════════════
setState() called after dispose(): _CupertinoControlsState#c4362(lifecycle state: defunct, not mounted)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Ahmadre** [comment]
Solved
