### ISSUE TITLE
[notwork in fullscreen] auto play next src

### ISSUE THREAD

**Issue by shiyiya** [brianegan/chewie#266]
```dart
initPlayer() async {
   
    _videoPlayerController = VideoPlayerController.network(src);
    _videoPlayerController.addListener(autoNextLis);

    _chewieController = ChewieController(
      videoPlayerController: _videoPlayerController,
      aspectRatio: 16 / 9,
      autoPlay: true,
      looping: false,
      allowedScreenSleep: false,
      allowFullScreen: true,
      allowMuting: false,
    );
    setState(() {});
  }

 autoNextLis() {
    int total = _videoPlayerController.value.duration?.inMilliseconds;
    final int pos = _videoPlayerController.value.position?.inMilliseconds ?? 0;

    if (total == null) total = 1;
    if (total - pos <= 0) {
      _videoPlayerController.removeListener(autoNextLis);
      if (currPlayIndex + 1 < videoList.length) toggleVideo(currPlayIndex + 1);
    }
  }

 toggleVideo(int i) async {
    if (i == currPlayIndex ||
        i > videoList.length - 1 ||
        (!_videoPlayerController.value.initialized &&
            !_videoPlayerController.value.hasError)) return;
    await _videoPlayerController.pause();
    currPlayIndex = i;
    await initPlayer();
  }
```

When the playback is finished, the next video is played, and the full-screen video is stopped, but the non-full-screen video is playing the next video (click back to see)！

**Comment by peakerWu** [comment]
@shiyiya   你好，全屏播放的时候，上一个播放完，自动播放下一个，你实现了吗

**Comment by shiyiya** [comment]
> @shiyiya 你好，全屏播放的时候，上一个播放完，自动播放下一个，你实现了吗

你可以看我 fork 的那份 找跳转全屏（全屏播放）那个代码文件的提交记录，原项目的判断似乎有点问题 我改了一下就好了

**Comment by peakerWu** [comment]
> > @shiyiya 你好，全屏播放的时候，上一个播放完，自动播放下一个，你实现了吗
> 
> 你可以看我 fork 的那份 找跳转全屏（全屏播放）那个代码文件的提交记录，原项目的判断似乎有点问题 我改了一下就好了
好的 非常谢谢  我去看下~

**Comment by peakerWu** [comment]
> > @shiyiya 你好，全屏播放的时候，上一个播放完，自动播放下一个，你实现了吗
> 
> 你可以看我 fork 的那份 找跳转全屏（全屏播放）那个代码文件的提交记录，原项目的判断似乎有点问题 我改了一下就好了

hello，我看提交那里没找到你提交的这个? 方便留个联系方式吗

**Comment by nstrelow** [comment]
Could you write english please?
or use emojis.

Just something, most people understand.

**Comment by shiyiya** [comment]
There is something wrong with the judgment here .    
 ↓ ↓ ↓
[here](https://github.com/brianegan/chewie/blob/master/lib/src/chewie_player.dart#L60)

**Comment by peakerWu** [comment]
> There is something wrong with the judgment here . ( I'm not sure, but I got the effect I wanted after the change)
> ↓ ↓ ↓
> [here](https://github.com/brianegan/chewie/blob/master/lib/src/chewie_player.dart#L60)

ok，thank you.

**Comment by peakerWu** [comment]
> There is something wrong with the judgment here . ( I'm not sure, but I got the effect I wanted after the change)
> ↓ ↓ ↓
> [here](https://github.com/brianegan/chewie/blob/master/lib/src/chewie_player.dart#L60)

ok，thank you.

**Comment by zoozobib** [comment]
> > There is something wrong with the judgment here . ( I'm not sure, but I got the effect I wanted after the change)
> > ↓ ↓ ↓
> > [here](https://github.com/brianegan/chewie/blob/master/lib/src/chewie_player.dart#L60)
> 
> ok，thank you.

请问您解决了吗？具体是怎么修改的？

**Comment by zoozobib** [comment]
> There is something wrong with the judgment here . ( I'm not sure, but I got the effect I wanted after the change)
> ↓ ↓ ↓
> [here](https://github.com/brianegan/chewie/blob/master/lib/src/chewie_player.dart#L60)

您好，求教您是如何修改的？我这边也出现了这个问题

**Comment by shiyiya** [comment]
@zoozobib  时间好久了 仓库更新这么久 有时间我再看看吧

**Comment by shiyiya** [comment]
#546

**Comment by zoozobib** [comment]
@shiyiya 感谢你的回复和支持！！！
