### ISSUE TITLE
请求地址

### ISSUE THREAD

**Issue by 15600717002** [brianegan/chewie#270]
经测试，只可以请求https，不支持请求http。。

**Comment by SHIELD7** [comment]
可以的，你不可以请求应该是因为android限制了只能https

**Comment by Ahmadre** [comment]
@15600717002 @SHIELD7 ???

**Comment by nstrelow** [comment]
Use english please!

Google Translate
- After testing, only https can be requested, but http is not supported.
- Yes, you can’t request it because android restricts only https

Thanks for solving
