### ISSUE TITLE
Is this package being maintained?

### ISSUE THREAD

**Issue by aytunch** [brianegan/chewie#275]
It seems the last commit was 4 months ago. I am asking for deciding to use this package in my project.

**Comment by Sub6Resources** [comment]
The primary developer is very busy, but yes, I believe this is still being maintained.

**Comment by cbenhagen** [comment]
Yes it is being maintained and used in production by many (myself included). I am helping Brian out with maintaining the package where my time permits but we could definitely need some more help.

**Comment by aytunch** [comment]
> Yes it is being maintained and used in production by many (myself included). I am helping Brian out with maintaining the package where my time permits but we could definitely need some more help.

@cbenhagen You are everywhere man:) keep up the good work.
