### ISSUE TITLE
Flutter has removed RouteSettings.isInitialRoute and it is preventing running of an app

### ISSUE THREAD

**Issue by dfmiller** [brianegan/chewie#279]
A recent update (https://github.com/flutter/flutter/pull/51435) has removed the isInitialRoute parameter from RouteSettings but it is still in the documentation (https://api.flutter.dev/flutter/widgets/RouteSettings-class.html) with no mention of the deprecation.

Compiler message:
/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/chewie-0.9.8+1/lib/src/chewie_player.dart:126:31: Error: No named parameter with the name 'isInitialRoute'.
      settings: RouteSettings(isInitialRoute: false),                   
                              ^^^^^^^^^^^^^^

**Comment by lmx01** [comment]
Do you reslove this problem?thanks

**Comment by masewo** [comment]
I fixed it in my fork:
https://github.com/masewo/chewie.git

If you have other dependencies that rely on chewie you can override it by:

```
dependency_overrides:
  chewie:
    git:
      url: https://github.com/masewo/chewie.git
```

**Comment by lmx01** [comment]
ok,thank U

**Comment by cbenhagen** [comment]
Thanks for reporting this issues. It has been fixed in version 0.9.10.

**Comment by the-pokman** [comment]
bonjour
quand je complie sa me donne se message serait vous comment je peut le résoudre ?  Launching lib\main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.

Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/youtube_player_flutter-1.1.1+1/lib/src/youtube_player.dart:310:31: Error: No named parameter with the name 'isInitialRoute'.
      settings: RouteSettings(isInitialRoute: false),
                              ^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/navigator.dart:458:9: Context: Found this candidate, but the arguments don't match.
  const RouteSettings({
        ^^^^^^^^^^^^^
Exited (1)

**Comment by stevebrainng** [comment]
> dependency_overrides:
>   chewie:
>     git:
>       url: https://github.com/masewo/chewie.git

Hi, @masewo After adding this to my pubspec.yaml I got the following  errors

```
Because every version of chewie from git depends on wakelock ^0.1.2 and better_player 0.0.37 depends on wakelock ^0.2.0+1, chewie from git is incompatible with better_player 0.0.37.

And because no versions of better_player match >0.0.37 <0.1.0, chewie from git is incompatible with better_player ^0.0.37.

So, because thekingsheritage_flutter depends on both better_player ^0.0.37 and chewie from git, version solving failed.
pub get failed (1; So, because thekingsheritage_flutter depends on both better_player ^0.0.37 and chewie from git, version solving failed.)
exit code 1
```

**Comment by nstrelow** [comment]
just use the official fixed chewie version.

Also you should probably use better_player or chewie not both
