### ISSUE TITLE
[Bug] portrait video being played while squished 

### ISSUE THREAD

**Issue by Dreamersoul** [brianegan/chewie#294]
when playing a video that is filmed in portrait the player squishes the video even when no aspect ratio has been provided to the widget.
can the video be played in the middle with black borders around it?

**Comment by Ahmadre** [comment]
You have to make sure your `VideoPlayerController` is initialized from `video_player` and give chewie then the controller to build. Follow this PR for more infos: https://github.com/brianegan/chewie/pull/289

**Comment by Dreamersoul** [comment]
thank you for pointing that out!

**Comment by Dreamersoul** [comment]
> You have to make sure your `VideoPlayerController` is initialized from `video_player` and give chewie then the controller to build. Follow this PR for more infos: #289
last question will this method work on what is on master now or should i wait for the PR?

**Comment by Ahmadre** [comment]
> > You have to make sure your `VideoPlayerController` is initialized from `video_player` and give chewie then the controller to build. Follow this PR for more infos: #289
> 
> last question will this method work on what is on master now or should i wait for the PR?

You don't need to wait. It is the actuall workflow to initialize before giving your VideoPlayerController to Chewie :). Go for it!

**Comment by Ahmadre** [comment]
For all who don't want to wait for the PR to land, add these lines to your pubspec.yaml:

```yaml
chewie:
  git:
    url: git://github.com/Ahmadre/chewie.git
    ref: Correct-Portrait
```
