### ISSUE TITLE
Video Player Fails to Switch to Landscape View in iOS

### ISSUE THREAD

**Issue by ArjunNagraj** [brianegan/chewie#299]
Video Player does not switch to landscape mode in iOS even on screen rotation.
Force setting the systemChrome deviceorientation to landscape crashes the app.

**Comment by ArjunNagraj** [comment]
Apologies the issue was with xcode setting so closing the issue.

**Comment by biklas7** [comment]
@ArjunNagraj I'm having the same problem. Can you tell me what you've changed? Thanks
