### ISSUE TITLE
Does chewie handle audio only files? Is there a plugin like chewie that does?

### ISSUE THREAD

**Issue by jeffmikels** [brianegan/chewie#30]
Sorry for asking this here, but does chewie handle audio files like mp3?

**Comment by brianegan** [comment]
Hey hey -- You might be able to use Chewie in this way (haven't tested), but really Chewie is meant for video playback and not a general purpose player like VLC. It'd probably be a bit better to investigate other options that are made for audio.

**Comment by fritz-playmaker** [comment]
> Hey hey -- You might be able to use Chewie in this way (haven't tested), but really Chewie is meant for video playback and not a general purpose player like VLC. It'd probably be a bit better to investigate other options that are made for audio.



> Sorry for asking this here, but does chewie handle audio files like mp3?

Check this Library out [](https://pub.dartlang.org/packages/flutter_sound)

**Comment by ronlinet** [comment]
It didn’t work in my case, I have tried m4a and mp3 . 
I found this => https://pub.dev/packages/chewie_audio/versions/1.0.0/example
