### ISSUE TITLE
chewie controls rebuilds

### ISSUE THREAD

**Issue by boucoding** [brianegan/chewie#308]
Hi,

I am using this plugin but I am facing a problem which is that the player controls rebuild continuously but the video itself doesn't rebuild and start from the beginning.

Here there is a link to a project I have created to reproduce the bug.

https://github.com/boucoding/visibility_detector_video_player_bug_sample

Thanks,

**Comment by jhomlala** [comment]
Check Better Player: https://github.com/jhomlala/betterplayer#betterplayerlistviewplayer
It supports playing videos in list and should solve your problem.

**Comment by boucoding** [comment]
I am sorry for the issue .

It was produced by another plugin 

Good day
