### ISSUE TITLE
Entering and leaving fullscreen overwrites device orientation settings

### ISSUE THREAD

**Issue by tsandoz** [brianegan/chewie#317]
Issue:
My app only allows portraitUp as device orientation.
When I enter and leave fullscreen mode in a video the app can enter any orientation mode.
Not only on the page the video is in, but everywhere.

Is there a way keep my orientation settings, or do I have to lock the orientation again after leaving fullscreen mode.

**Comment by pranavkpr1** [comment]
Use 
deviceOrientationsAfterFullScreen: [
            DeviceOrientation.portraitUp
          ],
in chewieController to keep the orientation to portrait after exiting fullscreen. Hope it helps!

**Comment by tsandoz** [comment]
Somehow I didn't see this option on the Controller. It's absolutely time for the Weekend.
Thank you very much.
