### ISSUE TITLE
Memory leak issue in video player with VideoPlayerController.network

### ISSUE THREAD

**Issue by SalilThreeplus** [brianegan/chewie#348]
Hello guys can anyone please help me with the below problem?
Error
A connection to http://flutter.github.io/ was leaked. Did you forget to close a response body?
Problem statement.
I am creating e-commerce app that has a carousel with video and images in it. For the video player I am using chewie and video_player plugins and for carousal I amusing carousel_slider.I have created a stateful widget according to chewie docs and returning that widget to carousal builder. The code is running but I am getting this memory leak error. Please help, thanks in advance. Attaching the snippet of chew class that loads video player and carousel slider.

`class Chew extends StatefulWidget {
Chew({Key key}) : super(key: key);
@override
_ChewState createState() => _ChewState();
}
class ChewState extends State {
ChewieController chewieController;
VideoPlayerController videoPlayerController;
Chewie playerWidget;
@override
void initState() {
super.initState();
var chewieController = ChewieController(
videoPlayerController: VideoPlayerController.network(
'http://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4')
..initialize().then(() {
setState(() {});
}),
// ..play(),
autoInitialize: false,
allowMuting: true,
aspectRatio: 3 / 2,
autoPlay: false,
looping: false,
showControlsOnInitialize: true,
);
playerWidget = Chewie(
controller: chewieController,
);
}
@override
Widget build(BuildContext context) {
return Container(
child: playerWidget,
);
}
@override
void dispose() {
videoPlayerController.dispose();
chewieController.dispose();
super.dispose();
}
}

CarouselSlider(
options: CarouselOptions(
height: 400.0,
viewportFraction: 0.8,
initialPage: 0,
enableInfiniteScroll: false,
reverse: false,
autoPlay: false,
// autoPlayInterval: Duration(seconds: 3),
// autoPlayAnimationDuration: Duration(milliseconds: 800),
autoPlayCurve: Curves.fastOutSlowIn,
enlargeCenterPage: true,
onPageChanged: (viewModel.onCarousalPageChanged()),
scrollDirection: Axis.horizontal,
),
items: [1, 2].map((value) {
return Builder(
builder: (BuildContext context) {
return Chew();
},
);
}).toList(),
)`

**Comment by Ahmadre** [comment]
Solved. Video was down
