### ISSUE TITLE
Buffering event and listener

### ISSUE THREAD

**Issue by vijaykanta** [brianegan/chewie#36]
I am pretty impressed with this player and have started using it already, however I don't see how I can implement the circle indicator when the video is buffering. I mean, there's no callback property as such where I can use a stack to show/hide indicator on top.

**Comment by bostrot** [comment]
Until there is you need to do it manually. E.g. something like this: ea8b62a577228145d79face28704dbb760459

**Comment by ThinOfSnowDance** [comment]
I want to know how to buffer video. Can you give me a demo?

**Comment by vijaykanta** [comment]
> Until there is you need to do it manually. E.g. something like this: [ea8b62a](https://github.com/brianegan/chewie/commit/ea8b62a577228145d79face28704dbb760459bad)

Nice one there, so you mean the _latestValue contains the buffering info? If yes, I think it's already implemented isn't it, I couldn't find in the APIs.

**Comment by cbenhagen** [comment]
@vijaykanta yes you can access this info from the controller. `Chewie` 1.0.0 and above will make it even easier to customise without forking the whole player.
