### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(5, null, null, video/avc, avc1.4D4032, 9728000, null, [1920, 1080, -1.0], [-1, -1]), null)

### ISSUE THREAD

**Issue by leejunofan** [brianegan/chewie#363]
am getting this error 
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(5, null, null, video/avc, avc1.4D4032, 9728000, null, [1920, 1080, -1.0], [-1, -1]), null)

i have used chewie controller and the scenario is :
its working fine when i visit first 3 to 4 times of video page but when i visit 5th time its getting error like above and i dont know how to fix this issue ... so please help me out from this error.... 

  void initState() {
    super.initState();
    videoPlayerController1 = VideoPlayerController.network(
        'https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8');
    chewieController = ChewieController(
      videoPlayerController: videoPlayerController1,
      aspectRatio: 3 / 2,
      autoPlay: true,
      looping: false,
      allowedScreenSleep: true)}

  @override
  void dispose() {
    videoPlayerController1.dispose();
    chewieController.dispose();
    super.dispose();
  }

if i done any mistake please correct it ...

**Comment by kamleshwebtech** [comment]
Your looks correct to me. BTW how did you fixed this issue? Please share your experience.

**Comment by easazade** [comment]
i'm having the same porblem in my new app

**Comment by nstrelow** [comment]
Chewie only handles the UI and not playing the video itself.

That is handled by video_player and the underlying implementation exoplayer.

I would advise you to check those repositories and try if you get the same error by only using video_player.

video_player issues: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+video_player
https://pub.dev/packages/video_player

Feel free to reopen if the problem only occurs when using chewie

**Comment by nstrelow** [comment]
Found an issue which contains your error:

https://github.com/flutter/flutter/issues/68896

**Comment by Ahmadre** [comment]
@leejunofan as @nstrelow already mention: this is (was) a video_player issue which should already be resolved, because I've checked the exoplayer versions and all kind of streaming codecs are supported:
![image](https://user-images.githubusercontent.com/18512224/98750650-cd4bfe00-23be-11eb-9d55-fee25fdc1825.jpeg)

And chewie is depending on the latest version.

One more thing: it you can't decide m3u8 streams, try to use the rtmp version/decoder of exoplayer. I used that in earlier projects with chewie 👍🏼
