### ISSUE TITLE
Controller '.dispose' explicit call never works

### ISSUE THREAD

**Issue by vijaykanta** [brianegan/chewie#37]
I am trying to play multiple videos one after the other by clicking thumbnails. More like a youtube kinda flow. I am aware to stop current video from playing (as I have to open the different video) I have to use following.
`videoController.pause()`
`videoController.dispose()`

These don't work, and the old video keeps playing in background after opening new video.

I also tried
`@override
void dispose() {
videoController.dispose();
super.dispose();
}`

in the main life cycle.

**Comment by vijaykanta** [comment]
Ok I could fix above issue by initializing the controller in the widget's initState() method instead of the build() method, I could now navigate to many videos in the middle of playing or end of playing. But I have a big resource issue here, after a few videos, the app either crashes due to memory overload or the phone gets disconnected to AS.

controller is declared as a private instance member of widget state class, other class methods push navigation to different pages where I actually call pause() and dispose().

**Comment by asapJ** [comment]
Same issue here,  after playing 2 videos,  the third view throws a platform error. 
But if I restart the app the same circle continues.. I.e after playing to videos, it crashes, then you have to restart app to play another two videos before it crashes

**Comment by asapJ** [comment]
@vijaykanta ,  how did you generate thumbnails for videos. Been trying to implement same but no luck.

**Comment by vijaykanta** [comment]
@asapJ Those were regenerated and coming from a web service. All I do is show them and add an action trigger (detector) to open the video page.

About the app crash, have you tried willPop? It sounds like I can go back to any page fresh after disposing the Current video.

**Comment by asapJ** [comment]
@vijaykanta  haven't  tried willPop, will check it out though. Thanks.
Working on a project that requires a gallery, just stuck on generating thumbnails for the videos.

**Comment by cbenhagen** [comment]
I guess we can close this right? Please feel free to reopen if you think this there is something we should do about this in `chewie`!
