### ISSUE TITLE
Chewie doesn't seem to support the latest version of video_player (0.11.0)

### ISSUE THREAD

**Issue by hugovangalen** [brianegan/chewie#370]
The instructions say to add these dependencies:

```
dependencies:
  chewie: <latest_version>
  video_player: <latest_version>
```

However, if the latest video_player is enabled in pubspec.yaml, the following error is outputted when running packages upgrade:
```
Because chewie >=0.9.6 depends on video_player >=0.7.0 <0.11.0 and my_app depends on video_player ^0.11.0, chewie >=0.9.6 is forbidden.
So, because my_app depends on chewie ^0.9.10, version solving failed
```

**Comment by jdevogelaere-rmdy** [comment]
Same issue!

**Comment by morr0ne** [comment]
It looks like video_player reached a stable api, quoting from the documentation

> The plugin has reached a stable API, we guarantee that version 1.0.0 will be backward compatible with 0.10.y+z. Please use video_player: '>=0.10.y+x <2.0.0' as your dependency constraint to allow a smoother ecosystem migration. For more details see: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0

It should be possible to use '>=0.10.y+x <2.0.0' without any breaking changes

**Comment by Ahmadre** [comment]
resolved 👌🏽
