### ISSUE TITLE
upgrade wakelock dependency

### ISSUE THREAD

**Issue by Omi231** [brianegan/chewie#373]
I am using wakelock package in my app for keeping screen on different pages. Looks like chewie also use that package. Upgrading wakelock to latest version gives an error:

`Because chewie 0.9.10 depends on wakelock ^0.1.2 and no versions of chewie match >0.9.10 <0.10.0, chewie ^0.9.10 requires wakelock ^0.1.2.

So, because CharityProject depends on both chewie ^0.9.10 and wakelock ^0.2.0, version solving failed.
pub get failed (1; So, because CharityProject depends on both chewie ^0.9.10 and wakelock ^0.2.0, version solving failed.)`

**Comment by maerlynflagg** [comment]
Yeah i have similar problem, because current chewie version uses old wakelock.

`Because flutter_html >=1.0.0 depends on chewie ^0.9.10 which depends on wakelock ^0.1.2, flutter_html >=1.0.0 requires wakelock ^0.1.2.`

**Comment by Ahmadre** [comment]
It's all updated and future safe now. Please update chewie 👍🏼
