### ISSUE TITLE
cache video

### ISSUE THREAD

**Issue by lisen87** [brianegan/chewie#374]
你好，How to cache video？

**Comment by shatanikmahanty** [comment]
[Flutter cache manager](https://pub.dev/packages/flutter_cache_manager) --> You can use this library to cache files locally and then fetch them using your own custom logic.

**Comment by nstrelow** [comment]
@shatanikmahanty Thanks for the suggestion :D

The caching of videos is also something more related to the underlying video_player, so maybe there are even more ideas.

Here after a quick search I found this (also using flutter_cache_manager): https://honesdev.com/playing-and-caching-videos-in-flutter/

**Comment by omidraha** [comment]
Related:
https://github.com/jhomlala/betterplayer/pull/123/files
