### ISSUE TITLE
Can we help maintaining?

### ISSUE THREAD

**Issue by nstrelow** [brianegan/chewie#375]
Hey, @brianegan . Awesome work on this package.
So many people use it and it is just a must for a great video player experience in Flutter.

Searching for chewie in pubspec.yaml on GitHub returns 1,308 results and that's only for GitHub. Very impressive!

I noticed that there are a lot of PRs and Issues opened and there has not been a commit for 6 months now.

Are you currently able to maintain this package? Can some people maybe pitch in and help out?
 
Good luck on everything you got going on :D

**Comment by robertoltrocha** [comment]
Hi,
Another problem is that other plugins are dependent on your plugin and this causes a ripple effect. Could you update the dependencies?
Grateful for the collaboration.

**Comment by syssam** [comment]
@nstrelow could you recreate a new package. The author is missing

**Comment by brianegan-wiredash** [comment]
> Are you currently able to maintain this package? 

Nope! I've been super busy this lately and had very little time for open source. 

  > Can some people maybe pitch in and help out?

Sure! Who wants to be a maintainer? Happy to add more folks to this project.

**Comment by brianegan** [comment]
Sorry, posted from my work account. Reposting on my open source account:

  > Are you currently able to maintain this package? 

Nope! I've been super busy this year and had very little time for open source. 

  > Can some people maybe pitch in and help out?

Sure! Who wants to be a maintainer? Happy to add more folks to this project.

**Comment by Vanessa-Berazategui** [comment]
There is a fix of video player with the solution for 'Fix a bug on Android when loading videos from assets would crash.' Could you update the dependencies?

Thanks!

**Comment by nstrelow** [comment]
@brianegan 
I would love to get chewie compatible with the newer version of video_player and flutter.
I could try and help here.

Not sure I can help with all the issues and PRs, as I am not using a lot of the features of chewie currently.
But I would try my best reviewing small PRs and using video_player 1.0.0

**Comment by Ahmadre** [comment]
@brianegan how about @nstrelow and me are going to maintain cheque? There's also a big requested PR from me which fixes Portrait/Landscape.

Please confirm as soon as you can :)

**Comment by brianegan** [comment]
@nstrelow @Ahmadre You've been added as collaborators to the Github project. Furthermore, I've given @Ahmadre access to upload new versions of Chewie to pub as well. 

Thanks for the help and effort all!

**Comment by Ahmadre** [comment]
> @nstrelow @Ahmadre You've been added as collaborators to the Github project. Furthermore, I've given @Ahmadre access to upload new versions of Chewie to pub as well. 
> 
> 
> 
> Thanks for the help and effort all!

Thanks @brianegan 🔥 Let's rock community 🔥

**Comment by Ahmadre** [comment]
@nstrelow I'll create a priority board in Trello or some other good Board for the most urgent issues/PR's and invite you there. Please also reach me via email for more.

**Comment by nstrelow** [comment]
@Ahmadre What about using Github so it is visible?

Or are the boards still not good enough?

**Comment by Ahmadre** [comment]
> @Ahmadre What about using Github so it is visible?
> 
> Or are the boards still not good enough?
> 
> @brianegan Thanks, we'll do our best 🎉

oh yeah perfect 🥳 never used github boards.

I'll check it out. Otherwise you're also free and welcome to do it. We're a team now 💪🏼

**Comment by Ahmadre** [comment]
@nstrelow Ok I created a board: https://github.com/brianegan/chewie/projects/1

You can close this issue if you want :) 👍
