### ISSUE TITLE
Customize Controls styles？

### ISSUE THREAD

**Issue by Lizhooh** [brianegan/chewie#38]
How should I customize the style of Controls, please give me a hint, thank you.

**Comment by brianegan** [comment]
Hey there -- You can change the colors by supplying either `materialProgressColors` or `cupertinoProgressColors`. Overall, Chewie is meant to be a good looking player out of the box, and limits the amount of customization you can do. For example, if you wanted to completely change the way the controls look, it'd probably be best to write your own UI layer on top of the video_player plugin.

**Comment by brianegan** [comment]
Yep, that's exactly right. Overall, the intention of this library isn't meant for complete customization, but rather for a "Good Default" that you can use out of the box. If you'd like full control over the look and feel, it's best for Fork this library and adjust the controls for your own project, or write your own UI layer on top of the core `video_player` package!
