### ISSUE TITLE
iOS apps with iOS 14 widget and chewie will get rejected on ITMS-90853: Invalid font

### ISSUE THREAD

**Issue by erickok** [brianegan/chewie#381]
If you add chewie to an iOS app that also has an iOS 14 widget (extension) and submit this for (TestFlight) review, it will get rejected:

> **ITMS-90853**: Invalid font - There was an error validating the font at 'Runner.app/Frameworks/App.framework/flutter_assets/packages/open_iconic_flutter/assets/open-iconic.woff'. Font not supported by platform. 

This is due to the dependency on `open_iconic_flutter` which embeds the open-iconic font in unsupported woff format. 

I am not sure why adding an iOS widget triggers this static analysis at Apple's side, but it is somewhat widely reported that it does, similar to how it did [in Flutter itself](https://github.com/flutter/flutter/issues/65991).

**Comment by Ahmadre** [comment]
@erickok Thank you sooo much for this! We already answered you in your related PR :)
