### ISSUE TITLE
Help: CoMaintainer needed!

### ISSUE THREAD

**Issue by brianegan** [brianegan/chewie#39]
Hey all! I've been getting more and more issues on this library, but don't have a much time to work on Chewie at the moment. I'm looking for someone who is willing to help maintain Chewie so we can help support folks and fix bugs at a faster rate!

If you're interested, please respond to this issue and we'll go from there :)

**Comment by Sub6Resources** [comment]
I don't have a whole lot of time myself, but I would be willing to contribute to maintaining this library.

**Comment by cbenhagen** [comment]
I'd also help out!

**Comment by brianegan** [comment]
Perfect! I'll give both of you access to the repo :)

**Comment by brianegan** [comment]
All right -- both of you are now collaborators on the repo :)

Please feel free to submit PRs / fixes / etc. If ya need help publishing to pub, happy to help figure that out when the time comes!
