### ISSUE TITLE
chewie logo

### ISSUE THREAD

**Issue by Ahmadre** [brianegan/chewie#392]
Actually chewie doesn't have a logo.

Maybe we should consider having a minimalistic, but eye catching logo for the upcoming release. I know the creator of chewie had "Chewbacca" in mind with "chewie". Maybe we can have something like the lights of the lightsabers as a Play-Button/Icon and/or something additional to it (a circle...a dark background like star wars...).

If this isn't relevant to you guys, don't hesitate to close this issue :)

**Comment by syssam** [comment]
why need a logo, it just a package.
