### ISSUE TITLE
Please set your constraint to video_player: '>=0.11.y+x <2.0.0'

### ISSUE THREAD

**Issue by wangbo4020** [brianegan/chewie#396]
This Flutter plugin provides an API for querying information about an application package.

**Please set your constraint to** `video_player: '>=0.4.y+x <2.0.0'`

## Backward compatible 1.0.0 version is coming 
The plugin has reached a stable API, we guarantee that version 1.0.0 will be backward compatible with 0.4.y+z. Please use `video_player: '>=0.4.y+x <2.0.0'` as your dependency constraint to allow a smoother ecosystem migration. For more details see: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0

**Comment by nstrelow** [comment]
What is the impact it has on you?
Can you describe a specific case this breaks or impacts users?

**Comment by wangbo4020** [comment]
Sorry, I fork it
