### ISSUE TITLE
Fullscreen mode by default

### ISSUE THREAD

**Issue by juanruben** [brianegan/chewie#40]
Hello.

I am trying to figure out how to load a video in fullscreen mode by default. 
How would you do it?
Thanks in advance.

**Comment by bostrot** [comment]
As of now you would need to edit the package itself. You could trigger `_pushFullScreenWidget(context);` in the initState of `chewie_player.dart`.

**Comment by brianegan** [comment]
Option has now been added to as of `0.8.0`. Thanks for the report!
