### ISSUE TITLE
[IOS BUG] SeekTo will affect playbackSpeed !!! 

### ISSUE THREAD

**Issue by mypridelife** [brianegan/chewie#405]
Description : When you set double speed playback, dragging the progress bar will invalidate the double speed, but the displayed double speed will not change.
Example: this repository example!

**Comment by nstrelow** [comment]
Good catch

**Comment by mypridelife** [comment]
This is the official `video_player` problem, I have informed them

**Comment by nstrelow** [comment]
@mypridelife can you link the issue?

**Comment by mypridelife** [comment]
Of course. [#71264](https://github.com/flutter/flutter/issues/71264)
