### ISSUE TITLE
Full screen video controls is not using customized theme color

### ISSUE THREAD

**Issue by hamxiaoz** [brianegan/chewie#408]
I'm using this method to override the colors for default video controls, and it works on non-fullscreen mode. However, when I enter full screen, the video controls defaults back to the original one (with white background):

- transparent background in non-fullscreen mode
![Screen Shot 2020-12-01 at 9 48 48 PM](https://user-images.githubusercontent.com/351827/100833531-00623a00-341f-11eb-9125-60e6ccdb1f2b.png)

- default white background in full screen mode
![Screen Shot 2020-12-01 at 9 49 13 PM](https://user-images.githubusercontent.com/351827/100833557-0eb05600-341f-11eb-9f5e-6c2d37f527df.png)

The customization code:

```
  Widget build(BuildContext context) {
    // ...

    return Theme(
      data: ThemeData(
        accentColor: Colors.white,
        dialogBackgroundColor: Color.fromRGBO(0, 0, 0, 0.2),
        platform: TargetPlatform.android,
        iconTheme: IconThemeData(
          color: Colors.white,
        ),
      ),
      child: Scaffold(
        body: Center(
          child: DefaultTextStyle(
            style: TextStyle(color: Colors.white),
            child: Chewie(
              controller: _chewieController,
            ),
          ),
        ),
      ),
    );
  }
```

From source, it looks like it's rebuilding the controls on full screen, but it should still utilize the Context of current theme right?
- rebuilding: https://github.com/brianegan/chewie/blob/bd51616b90a3658b7c7e6961fe8b4f8e905bb193/lib/src/chewie_player.dart#L115
- using theme: 
https://github.com/brianegan/chewie/blob/bd51616b90/lib/src/material_controls.dart#L123

Is this a bug? How do you customize the color without implementing a whole custom control?

**Comment by hamxiaoz** [comment]
UPDATE:

I ends up using this package [better player](https://pub.dev/packages/better_player), it's based on chewie but fixes a lot of issues including this one.

**Comment by nstrelow** [comment]
You are always free to make a Pull Request and add the changes you want ;)
