### ISSUE TITLE
chewie 0.12.0 doesn't install, but 0.9.10 version is normal

### ISSUE THREAD

**Issue by msidolphin** [brianegan/chewie#409]
Because flutter_html depends on chewie ^0.12.0 which doesn't match any versions, version solving failed.
pub get failed (1; Because flutter_html depends on chewie ^0.12.0 which doesn't match any versions, version solving failed.)

my environment:
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.14.5 18F203, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.51.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available

**Comment by syssam** [comment]
0.12 is latest version.
https://pub.dev/packages/chewie

**Comment by nstrelow** [comment]
You have to set chewie to it's latest version.

Closing, since this is not a problem with chewie.
