### ISSUE TITLE
onCompletionListener callback

### ISSUE THREAD

**Issue by juanruben** [brianegan/chewie#41]
Hi.

In the current state of the plugin is it possible to set a callback function to be called on finished video playing? The listener for VideoPlayerController does not seem to help a lot. I tried to make it somehow work, but it is not always called in Android.

**Comment by bostrot** [comment]
There is no such callback yet. You could hardcode it though by checking the duration of the video and the current state.

**Comment by markuspaschi** [comment]
You can simply add an onCompletionListener, where VideoWidgetState is the Constructor of my Video Class:
```

  VoidCallback onCompletionListener;
  VideoWidgetState() {
    onCompletionListener = () {
      if (!mounted) {
        return;
      }

      if (_controller.value.duration < _controller.value.position) {
        //next page. (we completed the video)
      }

      //setState(() {});
    };
  }
```

And add the listener to your controller in your init method:

`      ..addListener(onCompletionListener)`

**Comment by cbenhagen** [comment]
@juanruben you can do this by adding a listener to the `VideoPlayerController` like showed above. If there is something wrong with that controller please open an issue on flutter or ask on StackOverflow.

As I do not see anything to add on our side I think we can safely close this.
