### ISSUE TITLE
local video

### ISSUE THREAD

**Issue by fromparis** [brianegan/chewie#42]
```
new VideoPlayerController.asset(
      "assets/videos/test.mp4",
```

local videos crash...

**Comment by bostrot** [comment]
Add more details like crash report flutter doctor etc.

**Comment by cbenhagen** [comment]
For some reason assets do not load on for me when used in the chewie_example. But only on start. If I add them to one of the buttons it does work as expected.

**Comment by tikodrack** [comment]
videos don't crash on the emulator
but then, when trying on a real cell phone
downloading from the Play Store
then the whole App crashes...

**Comment by cbenhagen** [comment]
Can't reproduce this issue. Not on real devices and not on an emulator. @fromparis if you still see this when using `Chewie` but it works when using a plain `VideoPlayer`, please comment with a full example and the output of `flutter doctor` and I will reopen the issue.
