### ISSUE TITLE
The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.

### ISSUE THREAD

**Issue by Shvet** [brianegan/chewie#422]
I am using flutter_html and it depends on chewie lib, It was working fine before in flutter dev, but once i have changed channel to stable it give me error, 

```
[+15653 ms] [+30329 ms] /C:/Users/dhava/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/chewie-0.12.1+1/lib/src/chewie_player.dart:85:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
[        ] [   +3 ms]       resizeToAvoidBottomPadding: false,
[   +3 ms] [        ]       ^^^^^^^^^^^^^^^^^^^^^^^^^^
[   +3 ms] [        ] ../sdk/flutter/packages/flutter/lib/src/material/scaffold.dart:1437:9: Context: Found this candidate, but the arguments don't match.
[        ] [        ]   const Scaffold({
[        ] [        ]         ^^^^^^^^
[ +129 ms] [  +83 ms] /C:/Users/dhava/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/chewie_audio-1.1.1/lib/src/chewie_player.dart:99:17: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
[   +1 ms] [        ]  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../sdk/flutter/packages/flutter/lib/src/widgets/framework.dart').
[        ] [        ] Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
[   +1 ms] [        ]         context.inheritFromWidgetOfExactType(_ChewieAudioControllerProvider) as _ChewieAudioControllerProvider;
[   +2 ms] [        ]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I changed channels to stable, beta, dev and master one by one, but it is not working.

**Comment by pinpong** [comment]
https://github.com/brianegan/chewie/pull/423

**Comment by Shvet** [comment]
> #423

i have tried it but didnt work, I deleted folder from cache, but it is still same.

**Comment by nstrelow** [comment]
Is this a recent change in the flutter sdk?

Do you know which one is causing this?

**Comment by pinpong** [comment]
https://api.flutter.dev/flutter/material/Scaffold/resizeToAvoidBottomPadding.html

**Comment by nstrelow** [comment]
Nice thanks a lot :D

Will merge your PR

**Comment by pinpong** [comment]
Would be cool if you can publish a new version. Thanks.

**Comment by nstrelow** [comment]
Should have been solved by #423.

Thanks @pinpong

**Comment by Shvet** [comment]
[√] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [Version 10.0.19041.746], locale en-IN)
    • Flutter version 1.25.0-8.2.pre at D:\Android\sdk\flutter
    • Framework revision b0a2299859 (2 weeks ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Mi A1 (mobile) • 5f966a990504 • android-arm64  • Android 9 (API 28)
    • Chrome (web)   • chrome       • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)     • edge         • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!

**Comment by Shvet** [comment]
Ok Found Problem And solved, it was because of this [69620](https://github.com/flutter/flutter/pull/69620).

**Comment by nstrelow** [comment]
Nice, thanks for reporting back. Always helpful should somebody encounter the same problem
