### ISSUE TITLE
No named parameter with the name 'resizeToAvoidBottomPadding'.

### ISSUE THREAD

**Issue by taohuangtao** [brianegan/chewie#424]
pub-cache/hosted/pub.flutter-io.cn/chewie-0.12.0/lib/src/chewie_player.dart:85:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
      resizeToAvoidBottomPadding: false,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by nstrelow** [comment]
Should be fixed in 12.2

**Comment by nstrelow** [comment]
Please reopen, should this still not work for you after upgrading to 12.2
