### ISSUE TITLE
any one please help me how to set 15 sec fast forward and backward in android mode

### ISSUE THREAD

**Issue by shailendra-rajpoot** [brianegan/chewie#426]
i am new in flutter plz any one tell me how to set 15 sec fast forward and backward in android mode i need it urgent. 15 sec fast forward  and backward is already available in ios mode but not in android plz hell me how to do it in android mode

**Comment by nstrelow** [comment]
This is not implemented for Android. Please don't submit multiple issues

**Comment by shailendra-rajpoot** [comment]
please sir  implement it for android mode i need this functionality in urgent.
