### ISSUE TITLE
Migrate library to null safety

### ISSUE THREAD

**Issue by ueman** [brianegan/chewie#430]
The next stable release of Flutter is using most probably Darts new nullsafety feature.
Thus this library should be migrated.

Please see the following links for further information:
https://dart.dev/null-safety/migration-guide
https://medium.com/flutter/announcing-dart-null-safety-beta-4491da22077a?source=collection_home---4------3-----------------------

**Comment by miDeb** [comment]
I quickly put this pr together: #443

**Comment by nstrelow** [comment]
#443 is merged.
Will update package soon.

**Comment by nstrelow** [comment]
Published as 1.0.0
