### ISSUE TITLE
You must provide a chewie controller but I have it

### ISSUE THREAD

**Issue by Hekhy** [brianegan/chewie#432]
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building MyVideo(dirty, state: _MyVideoState#a1454):
You must provide a chewie controller
'package:chewie/src/chewie_player.dart':
Failed assertion: line 26 pos 16: 'controller != null'

The relevant error-causing widget was
MyVideo
lib\…\video_page\video_page.dart:31
When the exception was thrown, this was the stack
#2      new Chewie
package:chewie/src/chewie_player.dart:26
#3      _MyVideoState.build
package:san_valentin/…/components/videoPlayer.dart:63
#4      StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
#5      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
#6      StatefulElement.performRebuild

I always get this error although the player continues to work, but it makes a blank screen when I enter the screen where I am using the widget which is annoying and is an error.
Before I have not realized that it did, but I wanted to try the player package called better_player and since I did not like it, I decided to go back to chewie and since then it makes me this error.
Any help or ideas what can happen? I would not like to have to format windows just for that. But I need to compile the application and so it doesn't work well.

**Comment by nstrelow** [comment]
Please provide a failing example.

Also you're probably not initializing the player correctly.
Make sure to look at the example

**Comment by Hekhy** [comment]
This is the code for the widget. As I said before, it was fine and now it gives me that error in addition to a white screen.
I will check again, but esque had made copy and paste, I think that is strange.
![dfas](https://user-images.githubusercontent.com/70041483/107863374-3b87dd00-6e54-11eb-8fb9-92d965a518ed.png)
I also leave a screenshot of my screen with the console and a short video of how and when the error happens.
![dgfgsdf](https://user-images.githubusercontent.com/70041483/107863399-6ffb9900-6e54-11eb-9c0c-d46b9f00f5ac.jpg)

https://user-images.githubusercontent.com/70041483/107863401-71c55c80-6e54-11eb-81eb-28eb2557c027.mp4

**Comment by Hekhy** [comment]
Ok, sorry, but it is not setting the condition that verifies if the videocontroller is initialized and the chewie controler has value and that is why as it did not have the circular progress indicator it gave me that instant error.

What happened is that I was testing it with a lighter video that loaded so fast that it didn't give me an error and when I put another video on it, it gave me this error, that's why I said that before if it worked well for me.

**Comment by nstrelow** [comment]
Great that it's working now 🎉 

Happy Fluttering 🐦
