### ISSUE TITLE
[ Feature ] Passing in icons?  [In Progress]

### ISSUE THREAD

**Issue by jeremiahlukus** [brianegan/chewie#435]
Hey would you be open to passing in icons like the play/pause button in both cupertino_controls and material_control as non-required params? 
https://github.com/brianegan/chewie/blob/6efa51970f971dc49d03529e2ac95d92b9f1da3a/lib/src/cupertino_controls.dart#L342

This will make the package a bit more flexible for UI changes.

I can make a PR for this just seeing if this is something wanted.

**Comment by nstrelow** [comment]
Do you think people would like to display alternative icons there?

Generally I am not opposed (not sure about @brianegan or @Ahmadre ), if chewie can be more useful by providing the possibility to change the icons.
Only if it makes the code or plugin more complicated.

Are we allowing customization of icons anywhere currently?

**Comment by jeremiahlukus** [comment]
I have a need to pass in a custom icon for the play button (and modify the overlay but not doing that yet).

<img width="224" alt="Screen Shot 2021-02-16 at 7 08 59 AM" src="https://user-images.githubusercontent.com/17206638/108061110-d8e63b00-7025-11eb-8359-7bb002fce261.png">

**Comment by jeremiahlukus** [comment]
and of course if this is approved I'll send a PR to do the work 👍

**Comment by nstrelow** [comment]
Awesome, that's a great usecase, so feel free to add it.

Also maybe worth thinking if the icon is reused in places or if multiple icons can benefit from passing them.

Thanks for tackling this 💯

**Comment by jeremiahlukus** [comment]
Great ill start working on this and try to get it out in the next few days

**Comment by jeremiahlukus** [comment]
Ill do this on Monday have some deadlines....

**Comment by nstrelow** [comment]
Great, don't stress too much ;)

**Comment by jeremiahlukus** [comment]
Just looking at the code 
https://github.com/brianegan/chewie/blob/master/lib/src/cupertino_controls.dart#L254 

Is what controls the big play button, i think changing it to what i wanted would make the code a bit messy.

**Comment by nstrelow** [comment]
I see, I hope you can find some kind of workaround for your project

**Comment by basnetjiten** [comment]
any thing on this? couldn't find clue to use this feature

**Comment by mihalycsaba** [comment]
so does this work, I don't see where can I pass in custom icons for play/pause etc.

**Comment by jeremiahlukus** [comment]
No, if you go through the code you will see its using AnimatedIcon play_pause. When i looked at this a year ago added a icon param made it too messy, things might be different now.
