### ISSUE TITLE
Hide or disable progress bar

### ISSUE THREAD

**Issue by marianoarga** [brianegan/chewie#44]
Hello, how can I hide the progress bar, since I'm streaming live video and dont need it.
I have commented "_buildPosition" and "_buildProgressBar" but It'st really hacky and mess with controls distribution.

Could you add that feature?
Thank you.

**Comment by aqzwss** [comment]
+1

**Comment by cbenhagen** [comment]
Future versions of Chewie will make it easier to customize the controls. I will close this in favor of #100.
