### ISSUE TITLE
In urgent need of a method that provides download-speed of video for users!!!!

### ISSUE THREAD

**Issue by ZHUMINGZHE123** [brianegan/chewie#441]
In urgent need of a method like _mediaPlayer.getTcpSpeed()_ by _ijkPlayer-android_. It can provide download-speed of video for users

**Comment by nstrelow** [comment]
THIS IS NOT YOUR PERSONAL DEVELOPMENT TEAM!!!!

Your urgency is your problem and nothing here will be done urgently for you. That kind of asking really grinds my gears and it makes me want to work on everything except what you are demanding.

Also this will never be a part chewie. Chewie is only a UI for video_player.

**Comment by BROUDING** [comment]
LOL This made my day.
Should be the Issue of the year.
