### ISSUE TITLE
Hide play button until video has loaded

### ISSUE THREAD

**Issue by Sub6Resources** [brianegan/chewie#45]
With a network video, sometimes the video can take a couple seconds to load. The play button still shows up during this time and the user can press it. I can use a placeholder to show a `CircularProgressIndicator` but the play button sits in front of it, hiding it.

It would be great if the play button was hidden until the video had finished loading/initializing.

**Comment by bostrot** [comment]
Until there is some callback for this you have to do it by yourself. You could do something like this: ea8b62a577228145d79face28704dbb760459

**Comment by Sub6Resources** [comment]
This was fixed in Chewie version 0.7.0

**Comment by hanns2002** [comment]
@Sub6Resources where can I find Chewie version 0.7.0?

**Comment by Sub6Resources** [comment]
@hanns2002 The latest Chewie version includes these fixes. If you'd like to specifically use 0.7.0 in your app (which isn't recommended) you can set that in your pubspec.yaml instead of the most recent version.
