### ISSUE TITLE
Play / Pause events

### ISSUE THREAD

**Issue by agreensh** [brianegan/chewie#451]
It would be great to get notified on play / pause events. This is useful if you have videos in a list, and want to stop one if another is played (using the default overlay controls, not your own buttons).

**Comment by nstrelow** [comment]
is that not something, that should be handled by the underlying video_player?

**Comment by Ahmadre** [comment]
@agreensh You can listen to those events in your VideoPlayerController or your provided video_player controller in your chewiecontroller: `chewieController.videoPlayerController.value.isPlaying` or `chewieController.isPlaying`
