### ISSUE TITLE
Update Video_player

### ISSUE THREAD

**Issue by rlee1990** [brianegan/chewie#46]
Hi can you update video_player to as there is an issue with IOS in the 0.6.4 version and using Chewie always loads the 0.6.4 version.
`video_player:
    git:
      url: https://github.com/recastrodiaz/plugins.git
      path: packages/video_player  
      ref: f0ade3cf3e366ec1e93139458f2bdf32d243b2be
    version: ^0.6.5`

**Comment by rlee1990** [comment]
Because the_snab depends on chewie ^0.6.1 which depends on video_player ^0.6.0, video_player from hosted is required.
So, because the_snab depends on video_player from git, version solving failed.
pub get failed (1)

**Comment by cbenhagen** [comment]
I don't think it's a good idea to depend on an unreleased version in chewie. But nothing stops you to force this video_player version in your project.
