### ISSUE TITLE
Exit fullscreen, sound is also go on

### ISSUE THREAD

**Issue by JianYiLead** [brianegan/chewie#460]
I enter fullscreen and play. After a few seconds exit fullscreen, sound is also go on

**Comment by nstrelow** [comment]
The sound is still playing. 

That happens if you do not dispose the video controller onDispose.

See stackoverflow example: https://stackoverflow.com/questions/58618449/flutter-chewie-dispose-not-working-when-video-fullscreen-mode-was-used-landscap

**Comment by LeonFangCN** [comment]
@nstrelow  I did dispose and it can not enter fullscreen.
Error: A VideoPlayerController was used after being disposed.
And I do not  dispose when chewieController.isFullScreen is true, then Exit fullscreen, sound is also go on, so what should I do?

**Comment by Liberations** [comment]
same problem my code ... fullscreen exit ,sound still playing
`
 @override
  void dispose() {
    print('chewieController dispose');
    videoPlayerController?.pause();
    chewieController?.pause();
    videoPlayerController?.dispose();
    chewieController?.dispose();
    super.dispose();
  }
`
