### ISSUE TITLE
Wakelock plugin version increament

### ISSUE THREAD

**Issue by levent-kantaroglu** [brianegan/chewie#463]
When I try to increase wakelock plugin wakelock ^0.5.1, I got this problem
> Because chewie 1.0.0 depends on wakelock ^0.4.0 and no versions of chewie match >1.0.0 <2.0.0, chewie ^1.0.0 requires wakelock ^0.4.0.
So, because pepee_mobile depends on both chewie ^1.0.0 and wakelock ^0.5.1, version solving failed.

>pub get failed (1; So, because pepee_mobile depends on both chewie ^1.0.0 and wakelock ^0.5.1, version solving failed.)
exit code 1

**Comment by LeonFangCN** [comment]
Same issue, please update wakelock plugin

**Comment by ryanheise** [comment]
#464 has been merged but not released, and there's currently a penaly from pana:

<div class="pkg-report-header foldable-button" data-ga-click-event="toggle-report-section-dependency">
      <div class="pkg-report-header-icon">
          <img src="https://pub.dev/static/img/report-missing-icon-red.svg?hash=6llp1n1eb1t26uio9tcac9afvlighefb" class="pkg-report-icon">
      </div>
      <div class="pkg-report-header-title">Support up-to-date dependencies</div>
      <div class="pkg-report-header-score -is-red">
        <span class="pkg-report-header-score-granted">10</span>
        /
        <span class="pkg-report-header-score-max">20</span>
        <img src="https://pub.dev/static/img/report-foldable-icon.svg?hash=7h097the3aim0n0ajj7g8rpdgjjvknap" class="foldable-icon">
      </div>
    </div>
    <div class="foldable-content" style="display: block; max-height: none;">
      <div class="pkg-report-content">
        <div class="pkg-report-content-summary markdown-body">
          <h3><img class="report-summary-icon" src="https://pub.dev/static/img/report-missing-icon-red.svg?hash=6llp1n1eb1t26uio9tcac9afvlighefb"> 0/10 points: All of the package dependencies are supported in the latest version</h3>

Package | Constraint | Compatible | Latest
-- | -- | -- | --
cupertino_icons | ^1.0.2 | 1.0.3 | 1.0.3
flutter | flutter | 0.0.0 | 0.0.0
video_player | ^2.0.0 | 2.1.1 | 2.1.1
wakelock | ^0.4.0 | 0.4.0 | 0.5.2

</div></div></div>

**Comment by diegotori** [comment]
@nstrelow Is there any chance that we can please get a new pub.dev release as a result of this? Obviously after upgrading the rest of the dependencies?

**Comment by Ahmadre** [comment]
> @nstrelow Is there any chance that we can please get a new pub.dev release as a result of this? Obviously after upgrading the rest of the dependencies?

I already updated all version today. Please upvote and follow this PR: https://github.com/brianegan/chewie/pull/475

**Comment by Ahmadre** [comment]
Since v. 1.1.0 all versions are up to date. Please update your chewie versions 👍🏼
