### ISSUE TITLE
chewie-0.12.1+1 resizeToAvoidBottomPadding

### ISSUE THREAD

**Issue by ropi95** [brianegan/chewie#469]
`../../../.pub-cache/hosted/pub.dartlang.org/chewie-0.12.1+1/lib/src/chewie_player.dart:85:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
      resizeToAvoidBottomPadding: false,

`
on the reales not said the problem fixed on chewie-0.12.1+1, but not working on my flutter project, still show the error.. thank you

**Comment by riddhij16** [comment]
@ropi95 
Hey having the same issue.. have you found any solution?

Also getting.. Target of URI doesn't exist: 'package:chewie/chewie.dart'. after upgrading to latest 1.0.0 version..

**Comment by Ahmadre** [comment]
Thank you for this issue.

You're using old versions in your local pub package. 

Please update your dependencies offline and make sure you're using 1.0.0!

For further help, make yourself safe with: *.lock files and why you're NOT using 1.0.0 here.

Fix is already online
