### ISSUE TITLE
support custom RichText subtitles

### ISSUE THREAD

**Issue by ekuleshov** [brianegan/chewie#479]
Current subtitles support is limited to plain-text subtitles. Though some subtitle formats allow more advanced subtitle formatting. It would be great to support that in the custom subtitle builder.

**Comment by Ahmadre** [comment]
No it's not limited to anything. Please read our Readme-section about the builder-method for your subtitles: https://github.com/brianegan/chewie#subtitles

**Comment by ekuleshov** [comment]
> No it's not limited to anything. Please read our Readme-section about the builder-method for your subtitles

Please review my PR.

Yes, the subtitles builder can build custom rendering for subtitles, but the Subtitle class has the `text` field of type `String`. So, you can't stick custom data in there (and parsing it at the time when subtitles are shown is not a good idea. So, the main thing I changed type to `dynamic` and added example how to render RichText data

**Comment by ekuleshov** [comment]
It seems like to make subtitles to use generic value instead of String will require generic type all the way up to the `Chewie` widget.

All in all, it seems like coupling subtitles into every video control implementation is too restrictive. It would be better to decouple subtitles from that and use a separate widget overlay instead. Somewhat similar to what `subtitle_wrapper_package` does. Then generic type only need to be specified when configuring subtitles overlay.
