### ISSUE TITLE
the video player has sound but no image on ios device

### ISSUE THREAD

**Issue by Dawish** [brianegan/chewie#48]
ios the video player has sound but no image

**Comment by bostrot** [comment]
Add some code flutter doctor etc. otherwise people can't help you. Also which device you are using etc.

**Comment by SteveAlexander** [comment]
I'm seeing the same problem. Latest flutter master channel.

I can hear the sound, and the controls appear and work. But there is no video showing.

This is on an iPhone X simulator. I'll try some other devices.

![image](https://user-images.githubusercontent.com/4321921/44945847-ff2da700-ade8-11e8-8e13-7f5063b78acb.png)


Sample code:
```
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Chewie(
          VideoPlayerController.network(
            'https://www.sample-videos.com/video/mp4/240/big_buck_bunny_240p_10mb.mp4'
          ),
          aspectRatio: 3 / 2,
          autoPlay: true,
          looping: true,
        )
      )
    );
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.7.6-pre.20, on Mac OS X 10.13.6 17G2208, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by Sub6Resources** [comment]
That's a known issue with the video_player plugin (https://github.com/flutter/flutter/issues/14647). It should work fine on normal devices as opposed to the simulator though.

**Comment by cbenhagen** [comment]
Please reopen with more info if this happens on a real device.

**Comment by Abgaryan** [comment]
@cbenhagen  it happens also in real ios device (iPhone 5,iPhone 6s)

**Comment by cbenhagen** [comment]
Can you please provide the output of `flutter doctor -v` and a small example app where you see this behaviour?

**Comment by Abgaryan** [comment]
@cbenhagen  
The Player code 
```
 Container(
          child: Chewie(
            new VideoPlayerController.network(
                "https://static.driveddy.com//theory/1.1.02-049.mp4"
            ),
            aspectRatio: 3 / 2,
            autoPlay: true,
            looping: true,
          ),
      ), 
```


```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.27.1)
[✓] Connected devices (1 available)
```

**Comment by cristobal85** [comment]
Can you test with the video_player v0.6.4?? I had problems #52 but with this version it's fine.

**Comment by RIddhiIroid** [comment]
@cristobal85 Thank you so much, this version works perfect.

**Comment by rodrigonepomuceno** [comment]
Any solution for this case? I have the same problem for a few days now and I can't solve it. Has anyone managed to end this problem?

**Comment by markdean21** [comment]
We encounter this error today? We are using chewie: 0.9.8
  video_player: ^0.10.3+1
Any recommendations from you guys? Any solution?
Thank you.

**Comment by Maus3rSR** [comment]
@markdean21 
Maybe its related to video_player and not chewie
https://github.com/flutter/plugins/pull/1307

Im facing this issue only on iOs devices, and without chewie Im facing same issue.

I'm really stupefied why a bug like this on a video player plugin still exist..

**Comment by Colir** [comment]
@Maus3rSR I can confirm that this bug is related to video_player https://github.com/flutter/flutter/issues/56431#issuecomment-692677106
