### ISSUE TITLE
Videoplayer not working properly on ios 14.5

### ISSUE THREAD

**Issue by xlcod** [brianegan/chewie#489]
Hi, i experienced a problem using chewie on flutter 1.22.6 and ios 14.5.

The problem: Videoplayer sometimes doesn´t show  the speed button and also i cant scroll through the video and resets himeself, the duration of the video its always 1h also.

I tried this on an iphone with 14.4 and works fine  , for the time being we are having this problem with  IOS 14.5 

`════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during paint():
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37: '<optimized out>'

The relevant error-causing widget was
Chewie
lib/Common/chewie_list_item.dart:57
When the exception was thrown, this was the stack
#2      _rrectIsValid (dart:ui/painting.dart:37:10)
#3      Canvas.drawRRect (dart:ui/painting.dart:3742:12)
#4      _ProgressBarPainter.paint
package:chewie/src/cupertino_progress_bar.dart:137
#5      RenderCustomPaint._paintWithPainter
package:flutter/…/rendering/custom_paint.dart:531
#6      RenderCustomPaint.paint
package:flutter/…/rendering/custom_paint.dart:572
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#77251
RenderObject: RenderCustomPaint#77251
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=552.0, h=47.0)
    size: Size(552.0, 47.0)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37: '<optimized out>'

The relevant error-causing widget was
Chewie
lib/Common/chewie_list_item.dart:57
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37: '<optimized out>'

The relevant error-causing widget was
Chewie
lib/Common/chewie_list_item.dart:57
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37: '<optimized out>'

`
Thanks :)

**Comment by Ahmadre** [comment]
Could you please try again with latest chewie: 1.2.1? We updated the video_player dependency. 

For further issues on these low level stuff: Please file an issue in video_player plugin
