### ISSUE TITLE
Fullscreen events

### ISSUE THREAD

**Issue by lgArlequin** [brianegan/chewie#49]
Hello, is there any way to access the events when the video comes out of full screen?
Because my application runs in full screen and leaves it when I leave a video in full screen.
I need my application to return to full screen.
Thanks!
Sorry for my english.

**Comment by lgArlequin** [comment]
Also, something not so complicated would be the possibility of being able to hide the full screen button.

**Comment by Sub6Resources** [comment]
So maybe something like an `allowFullscreen` parameter that defaults to true?

**Comment by cbenhagen** [comment]
Hey @lgArlequin, starting from `Chewie` 1.0.0 you can add a listener to the `ChewieController` to get notified on entering and leaving full screen mode. You can check my branch in #99. If it has not been released when you see this.
