### ISSUE TITLE
How to remove the options - (playback speed option.)?

### ISSUE THREAD

**Issue by AbhinaiVatsal** [brianegan/chewie#491]
I don't want the show the options , how to remove them for the player, Attached images for reference.
![Screenshot_1623058808](https://user-images.githubusercontent.com/17844907/120995335-effe9380-c7a2-11eb-8992-dc7ad7a69f2c.png)
![Screenshot_1623058830](https://user-images.githubusercontent.com/17844907/120995357-f42ab100-c7a2-11eb-9805-1e8f84ab06c8.png)

**Comment by QJJMSK** [comment]
you can override the function

**Comment by AbhinaiVatsal** [comment]
which function ?

**Comment by Ahmadre** [comment]
`showOptions` flag is coming... one minute

**Comment by Ahmadre** [comment]
@AbhinaiVatsal fixed in 1.2.1 Please update 👍
