### ISSUE TITLE
Some vids only work in Full Screen

### ISSUE THREAD

**Issue by brianegan** [brianegan/chewie#5]
Reported via email:

I love this package, however I have had an issue where some links only work in fullscreen mode. I'm testing on an android.

Links such as this work fine with the video player plugin but not in chewie. When I hit play the UI disappears and then when I can accidentally tap where the fullscreen should be the video will work in fullscreen mode.

https://i.imgur.com/TKL8h8J.mp4

**Comment by brianegan** [comment]
Note from the author: I tested this video and it "works on my machine." Might need to test a few more scenarios to see if I can reproduce the issue locally.

**Comment by seklum** [comment]
I'm the one that reported this issue. I've confirmed so far that the file does work properly in the example code on my device. On a file with audio that has the same problem it will play the sound in the background. The buffer seems to work but the time display shows 00:00/00:00 still. I can play/pause but the button does not change to the pause icon.

When I tap the fullscreen button it restarts with a new instance of the video. Going in and out of fullscreen causes multiple instances of the file to play in the background.

**Comment by brianegan** [comment]
Cool, thanks for the feedback. I'll test that scenario a bit more as well!

**Comment by seklum** [comment]
The video continuing to play in the background seems to be caused by the video player plugin and not chewie.

**Comment by brianegan** [comment]
Hey, as a heads up, I've bumped to the latest version of the video_player. I couldn't hear any audio playing in the background in the example when I move into a full screen view, but please let me know if your'e still experiencing that bug!
