### ISSUE TITLE
Can You Update Your Version Constraint?

### ISSUE THREAD

**Issue by Txurruka** [brianegan/chewie#50]
Can you update your version constraint? It's currently set at:

"<2.0.0"

The most recent stable version of Dart, as far as I know, is 2.1.0

**Comment by Sub6Resources** [comment]
This was fixed in version 0.7.0 a couple days ago and the constraint in pubspec.yaml is now `">=2.0.0-dev.28.0 <3.0.0"`. Make sure you're on version 0.7.0 and you should be good to go!
