### ISSUE TITLE
updated video player 0.7.5

### ISSUE THREAD

**Issue by Seifon** [brianegan/chewie#51]
has Exception

I/dalvikvm( 5366): Could not find method android.graphics.SurfaceTexture.setOnFrameAvailableListener, referenced from method io.flutter.view.FlutterView$SurfaceTextureRegistryEntry.<init>
W/dalvikvm( 5366): VFY: unable to resolve virtual method 697: Landroid/graphics/SurfaceTexture;.setOnFrameAvailableListener (Landroid/graphics/SurfaceTexture$OnFrameAvailableListener;Landroid/os/Handler;)V
D/dalvikvm( 5366): VFY: replacing opcode 0x6e at 0x0015
E/flutter ( 5366): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: android.graphics.SurfaceTexture.setOnFrameAvailableListener
E/flutter ( 5366): 	at io.flutter.view.FlutterView$SurfaceTextureRegistryEntry.<init>(FlutterView.java:969)
E/flutter ( 5366): 	at io.flutter.view.FlutterView.createSurfaceTexture(FlutterView.java:955)
E/flutter ( 5366): 	at io.flutter.plugins.videoplayer.VideoPlayerPlugin.onMethodCall(VideoPlayerPlugin.java:291)
E/flutter ( 5366): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/flutter ( 5366): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/flutter ( 5366): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 5366): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/flutter ( 5366): 	at android.os.Looper.loop(Looper.java:150)
E/flutter ( 5366): 	at android.app.ActivityThread.main(ActivityThread.java:5323)
E/flutter ( 5366): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter ( 5366): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/flutter ( 5366): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
E/flutter ( 5366): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
E/flutter ( 5366): 	at dalvik.system.NativeStart.main(Native Method)
E/flutter ( 5366): 
F/flutter ( 5366): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
F/libc    ( 5366): Fatal signal 6 (SIGABRT) at 0x000014f6 (code=-6), thread 5366 (ive.mysterylive)
handle_request(15)

**Comment by bostrot** [comment]
There is no `video_player` v0.7.5. Even if, this sounds like a `video_player` related issue so you should post the issue in the package's GitHub.

**Comment by cbenhagen** [comment]
I am closing this. Please reopen if you think this has something todo with chewie.
