### ISSUE TITLE
chewie 1.2.2 depends on provider ^5.0.0 but current provider  version is ^6.0.0

### ISSUE THREAD

**Issue by swarup13** [brianegan/chewie#530]
Because chewie 1.2.2 depends on provider ^5.0.0 and no versions of chewie match >1.2.2 <2.0.0, chewie ^1.2.2 requires provider ^5.0.0.
So, because jobspri depends on both provider ^6.0.0 and chewie ^1.2.2, version solving failed.

**Comment by yaochangliang159** [comment]
i meet the same question,how to resolve?

**Comment by robert-virkus** [comment]
Thanks for giving the correct hint @ducnm98 ! 
@yaochangliang159 go to `flutter\.pub-cache\hosted\pub.dartlang.org\chewie-1.2.2` and edit the _pubspec.yaml_ file there.

**Comment by invitro** [comment]
For temporary fix, I'm doing like this:

dependency_overrides:
  provider: ^6.0.0 # for chewie 1.2.2

more clean and we can remove after the package updated

**Comment by joelbrostrom** [comment]
We're having trouble playing videos on iOS.  
We just implemented the package into our project and run it with Provider 6.0.0 as suggested above.  
The video loads but we get no image and the play button does not start the video.
Have any one who used it pre 6.0.0 override experienced similar issues?

**Comment by Threehair** [comment]
> For temporary fix, I'm doing like this:
> 
> ```
> dependency_overrides:
>   provider: ^6.0.0 # for chewie 1.2.2
> ```
> 
> more clean and we can remove after the package updated

[https://dart.dev/tools/pub/dependencies#dependency-overrides](url)
>  _Warning: Using a dependency override involves some risk. For example, using an override to specify a version outside the range that the package claims to support, or using an override to specify a local copy of a package that has unexpected behaviors, may break your application._

**Comment by mustafa-707** [comment]
same here
