### ISSUE TITLE
Because chewie >=1.2.0 depends on provider ^5.0.0 and flutter_base depends on provider 6.0.0, chewie >=1.2.0 is forbidden.

### ISSUE THREAD

**Issue by yaochangliang159** [brianegan/chewie#533]
Because chewie >=1.2.0 depends on provider ^5.0.0 and flutter_base depends on provider 6.0.0, chewie >=1.2.0 is forbidden.
So, because flutter_base depends on chewie 1.2.2, version solving failed.
pub get failed (1; So, because flutter_base depends on chewie 1.2.2, version solving failed.)

this is my flutter doctor screencap:
<img width="585" alt="QQ20210903-172753@2x" src="https://user-images.githubusercontent.com/13497352/131983426-682c6f63-8bdf-4a1a-8799-007b67579ef1.png">

<img width="754" alt="QQ20210903-172923@2x" src="https://user-images.githubusercontent.com/13497352/131983651-ba168e8d-06a1-4c1d-83dc-d0f47cf539f0.png">

**Comment by Ahmadre** [comment]
Please make yourself aware of Flutters: https://dart.dev/tools/pub/dependencies#dependency-overrides

You only have to set:

```yaml
dependency_overrides:
  provider 6.0.0
```

All in all: remember that  this will also happen in most of the cases for plugins/packages that are not on latest packages. If in this case (5 -> 6), the APIs didn't change a lot or have breaking changes, you are safe with overrides.
