### ISSUE TITLE
flutter2.5 exit fullScreen crash

### ISSUE THREAD

**Issue by xtuck** [brianegan/chewie#538]
2021-09-13 10:37:23.504828+0800 Runner[12535:1425599] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Corrupted standard message'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20422de3 +[NSException raise:format:] + 0
	3   Foundation                          0x00007fff207748e7 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   Flutter                             0x0000000104f8be46 -[FlutterStandardReader readValueOfType:] + 151
	5   Flutter                             0x0000000104f8bfc1 -[FlutterStandardReader readValueOfType:] + 530
	6   Flutter                             0x0000000104f8a4bc -[FlutterStandardMessageCodec decode:] + 84
	7   Flutter                             0x0000000104f882db __48-[FlutterBasicMessageChannel setMessageHandler:]_block_invoke + 43
	8   Flutter                             0x0000000104a3ad29 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE + 193
	9   Flutter                             0x0000000104a40011 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE + 35
	10  Flutter                             0x0000000104de5817 _ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter5Shell29OnEngineHandlePlatformMessageENS_10unique_ptrINS5_15PlatformMessageENS_14default_deleteIS8_EEEEE4$_16EENS_9allocatorISD_EEFvvEEclEv + 81
	11  Flutter                             0x0000000104d6ef02 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 164
	12  Flutter                             0x0000000104d743fc _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	13  CoreFoundation                      0x00007fff2039178a __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	14  CoreFoundation                      0x00007fff2039127c __CFRunLoopDoTimer + 924
	15  CoreFoundation                      0x00007fff2039081a __CFRunLoopDoTimers + 265
	16  CoreFoundation                      0x00007fff2038ae69 __CFRunLoopRun + 2013
	17  CoreFoundation                      0x00007fff2038a1a7 CFRunLoopRunSpecific + 567
	18  GraphicsServices                    0x00007fff2b874d85 GSEventRunModal + 139
	19  UIKitCore                           0x00007fff246c14df -[UIApplication _run] + 912
	20  UIKitCore                           0x00007fff246c639c UIApplicationMain + 101
	21  Runner                              0x00000001037208fa main + 122
	22  libdyld.dylib                       0x00007fff2025abbd start + 1
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Corrupted standard message'
terminating with uncaught exception of type NSException
CoreSimulator 757.5 - Device: iPhone 12 mini (8C3BA0A7-5D9C-4333-B65D-DA176AB3F9FA) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 12 mini

**Comment by Brazol** [comment]
I have the same error, why did you close it @xtuck have you found the issue?

**Comment by xtuck** [comment]
> I have the same error, why did you close it @xtuck have you found the issue?

upgrade wakelock to newest(0.5.6)

**Comment by Brazol** [comment]
thanks!
