### ISSUE TITLE
aspectRatio cannot be set automatically

### ISSUE THREAD

**Issue by lebow01** [brianegan/chewie#54]
aspectRatio causes my video to be distorted I can't find a better solution

**Comment by lebow01** [comment]
final Size size = controller.value.size;
      return Center(
        child: AspectRatio(
          aspectRatio: size.width / size.height,
          child: VideoPlayPause(controller),
        ),
      );

**Comment by oscarwong67** [comment]
it seems like you have to fetch that size data after the videocontroller is initialized, but before the call to build Chewie

**Comment by I-am-original** [comment]
@brianegan I have the same question for now. I have places controller init in initState. Fetching size in Build before widget creation. Crashing with NPE. Are there any chance to get actual video resolution?

**Comment by cbenhagen** [comment]
@lebow01 please provide a full example and the output of `flutter doctor` if the comment above did not help you fix this. I will happily reopen the issue.
