### ISSUE TITLE
Fullscreen aspect ratio

### ISSUE THREAD

**Issue by patrickbz** [brianegan/chewie#55]
Hi!
When switching fullscreen the aspect ratio is not respected, the video is always strechted to the size of the screen 

If the videoplayer is wrapped in a AspectRatio also with the condition "widget.fullScreen && MediaQuery.of(context).orientation == Orientation.landscape" in "player_with_controls.dart" then the aspect ratio seems to be preserved

Thank you!

**Comment by lebow01** [comment]
How do I adjust the AspectRatio in full screen?

**Comment by lebow01** [comment]
Video will distort when full screen.

**Comment by patrickbz** [comment]
I changed this in lib/src/player_with_controls.dart:

@@ -48,7 +48,10 @@
         width: MediaQuery.of(context).size.width,
         child: widget.fullScreen &&
                 MediaQuery.of(context).orientation == Orientation.landscape
\-            ? _buildPlayerWithControls(controller, context)
\+            ? new AspectRatio(
\+                aspectRatio: widget.aspectRatio,
\+                child: _buildPlayerWithControls(controller, context),
\+              )
             : new AspectRatio(
                 aspectRatio: widget.aspectRatio,
                 child: _buildPlayerWithControls(controller, context),

@@ -69,7 +72,10 @@
               child: widget.fullScreen &&
                       MediaQuery.of(context).orientation ==
                           Orientation.landscape
\-                  ? new VideoPlayer(controller)
\+                  ? new AspectRatio(
\+                      aspectRatio: widget.aspectRatio,
\+                      child: new VideoPlayer(controller),
\+                    )
                   : new AspectRatio(
                       aspectRatio: widget.aspectRatio,
                       child: new VideoPlayer(controller),

and it seems working with correct aspect ratio also in fullscreen. I only specify the aspect ratio in Chewie with aspectRatio.

**Comment by Sub6Resources** [comment]
Go ahead and open a pull request with your changes and we'll do some more testing to make sure we don't get any unexpected results.

**Comment by brianegan** [comment]
Published as part of `0.8.0`. Thanks again!
