### ISSUE TITLE
videoplayer has error com.google.android.exoplayer2 ExoPlaybackException

### ISSUE THREAD

**Issue by lebow01** [brianegan/chewie#57]
My video prompts an error when playing repeatedly. The position of the progress bar.
![image](https://user-images.githubusercontent.com/23068980/46451790-e7bc5200-c7ca-11e8-854e-e23ac56c9ea0.png)
It's normal at the beginning, and I will have this problem when I open the video frequently.

I/ExoPlayerImpl(22488): Release a840477 [ExoPlayerLib/2.8.0] [HWRNE, RNE-L22, HUAWEI, 26] [goog.exo.core]

E/ExoPlayerImplInternal(22488): Caused by: android.media.MediaCodec$CodecException: start failed
E/ExoPlayerImplInternal(22488): 	at android.media.MediaCodec.native_start(Native Method)
E/ExoPlayerImplInternal(22488): 	at android.media.MediaCodec.start(MediaCodec.java:2063)
E/ExoPlayerImplInternal(22488): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:421)
E/ExoPlayerImplInternal(22488): 	... 8 more
E/ExoPlayerImplInternal(22488): Stop failed.

**Comment by lebow01** [comment]
> Same issue

I already know the answer to the question. Because when we initialize, we get the aspectRatio of the video

_controller = new VideoPlayerController.network(
      apiUrl + _dataJson["waterMarkVideoPath"],
    );
    _controller.addListener(() {
      if (_controller.value.size != null) {
        setState(() {
          valueSize = _controller.value.size;
        });
      }
    });

can not
//      ..initialize().then((_) {
//        setState(() {
//          valueSize = _controller.value.size;
//          initialized = _controller.value.initialized;
//        });
//      });
//    _controller.initialize().then((e){
//      setState(() {
//          valueSize = _controller.value.size;
//          initialized = _controller.value.initialized;
//        });
//    });

**Comment by localpcguy** [comment]
Running into this same issue, is there a known fix for it? I'm not clear on what it is from the above comment.

**Comment by cbenhagen** [comment]
The above issue does not look like something we can fix in `Chewie`. It does not look like a size issue but if you want to know the size of the video you will need to add a listener to the `VideoPlayerController` like in the comment above. 

@localpcguy, if you haven't already, please try if you can reproduce the issue with a plain `VideoPlayer` and if so, file an issue with a small demo `main.dart` and the output of `flutter doctor` in the main flutter repository.
