### ISSUE TITLE
RTMP Player

### ISSUE THREAD

**Issue by TheExeLab** [brianegan/chewie#59]
Hi! I need to play an RTMP stream (I don't want to use hls) but I don't find the way for doing that. How I can play it with Flutter?

Thanks!

**Comment by brianegan** [comment]
Hey there -- this plugin just uses the raw `video_player` plugin under the hood. Looks like details on supporting RTMP can be found here: https://github.com/flutter/plugins/pull/597

**Comment by TheExeLab** [comment]
When trying to play RTMP Stream in Flutter, ExoPlayer throws a Source error.

### Version of ExoPlayer being used
2.8.0

### Device(s) and version(s) of Android being used
Android 9

### Error thrown
https://pastebin.com/grw8ZrDZ

**Comment by Ahmadre** [comment]
@byeze it's working, but you have to activate the extension.

Just add:

```gradle
    implementation 'com.google.android.exoplayer:extension-rtmp:2.10.5'
```

to your main build.gradle :)
