### ISSUE TITLE
Two parameters not defined after flutter packer upgrade

### ISSUE THREAD

**Issue by stemuk** [brianegan/chewie#6]
After the use of Flutter Packages upgrade the parameters `handleColor` and `disabledColor` of `progressColors: new VideoProgressColors(..)` are not defined, although they are described in the example as "Try playing around with some of these other options".
Are they simply no longer necessary or is this a bug? Thanks anyway for the awesome chewie package!

**Comment by brianegan** [comment]
Hey hey :) Thanks for writing in!

Looks like I need to bump to the latest video_player plugin and refactor a bit with the changes. 

On vacation for a few days, but I'll try to get to it early next week :)

**Comment by stemuk** [comment]
@brianegan Have you already found the time to bump chewie to the latest video_player plugin?

**Comment by brianegan** [comment]
Almost good to go... will publish a new version tomorrow

**Comment by stemuk** [comment]
Glad that you are closing this so quickly, and thanks again for your awesome work!
