### ISSUE TITLE
video can not play on iOS device

### ISSUE THREAD

**Issue by wangyongpenga** [brianegan/chewie#60]
this demo can run on android phone all right ,but can not play video on iOS devices. and notes that:Failed to load video:the operation could not completed

**Comment by Sub6Resources** [comment]
What device are you using?

**Comment by I-am-original** [comment]
I have tried to run video playback on iPhone XR (Simulator) using Chewie or latest Video_player - for both cases it was not working at all on iOS

**Comment by Sub6Resources** [comment]
This is a known issue with the `video_player` plugin. It won't work on any iOS simulator.

**Comment by epenli** [comment]
i have the same problem when use local file.....
