### ISSUE TITLE
Not supported with the most recent version of video_player

### ISSUE THREAD

**Issue by rlee1990** [brianegan/chewie#63]
I receive this error.
`Because flutter_app depends on chewie ^0.7.0 which depends on video_player ^0.6.0, video_player ^0.6.0 is required.
So, because flutter_app depends on video_player ^0.7.2, version solving failed.`

**Comment by Sub6Resources** [comment]
Pull request #62 should fix this. Watch that for updates.

**Comment by brianegan** [comment]
Updated as part of `0.8.0`. Thanks for the report!
