### ISSUE TITLE
Feature Request: Add support for Youtube videos, add suport for PiP

### ISSUE THREAD

**Issue by asapJ** [brianegan/chewie#68]
would  be great if both features are added. meets a lot of unsolved use cases..

**Comment by asapJ** [comment]
@juanjoserodrigolazaro 
Doesn't support  all videos,  e.g music videos.

**Comment by wilsharo** [comment]
Using this package I was able to decode links for all YouTube videos, including music and play them in the chewie player just fine. Hope it helps.

https://pub.dartlang.org/packages/flutter_youtube_extractor#-example-tab-

**Comment by brianegan** [comment]
I agree with @cbenhagen -- It seems like what's needed is a way to async fetch the proper video url from a normal youtube link. Since there are packages out there which handle this, I don't think it should be core Chewie functionality. I'd definitely recommend one of the options suggested!
