### ISSUE TITLE
Accessing/viewing errors

### ISSUE THREAD

**Issue by mclark4386** [brianegan/chewie#70]
I'm currently getting a view that looks like this: 
<img width="315" alt="screen shot 2018-11-26 at 5 32 57 pm" src="https://user-images.githubusercontent.com/484943/49048743-7c2aab80-f1a1-11e8-82ec-a24d73da6e57.png">
and was wondering if there is some way to access that error so that I could actually see what it was saying and act on it?

**Comment by Sub6Resources** [comment]
You can look at the log in the IDE you are using. I agree though, the placement of the error messages isn't the best.

**Comment by mclark4386** [comment]
@Sub6Resources  I don't see anything in the console :-/  Maybe I'm just missing it... would it start like that error there?

**Comment by Sub6Resources** [comment]
No, not usually. What IDE are you using?

**Comment by mclark4386** [comment]
Android Studio, I'm seeing loads of logs that I'm printing out, but nothing about an error from the video player/controller.

**Comment by mclark4386** [comment]
@Sub6Resources is there any way to listen for errors or access them in any way? @brianegan ?

**Comment by mclark4386** [comment]
So for anyone looking for how to do this here is what I ended up with to get the full error message:
```
        controller.addListener(() =>
            (controller.value.hasError ? print("Controller error:${controller.value.errorDescription}") : null));
```
