### ISSUE TITLE
Green line in some videos

### ISSUE THREAD

**Issue by juanjoserodrigolazaro** [brianegan/chewie#71]
hello, i made an app to see videos with this plugins, in my phone samsung galaxy s8 works perfect but in some phones some wird green line appears i dont know why but you cant see videos with that. 

image: 

![image](https://user-images.githubusercontent.com/29029673/49467031-452b4a00-f7e0-11e8-9360-f00cd520b4bc.png)

**Comment by Sub6Resources** [comment]
I'd imagine this is an issue with the `video_player` plugin itself, not Chewie.

**Comment by cbenhagen** [comment]
If you can still reproduce this issue with the latest `video_player`, please file an issue on the flutter repository with a demo `main.dart` file and the output of `flutter doctor`.
