### ISSUE TITLE
Compatibility on mobile phones

### ISSUE THREAD

**Issue by huxiulin12** [brianegan/chewie#74]
The incompatibility between Red Rice and other Android phones, the lack of video interface, and the collapse of the entire app.

**Comment by Sub6Resources** [comment]
Your issue is unclear. Are you getting an error? If so, please post it here as well as the result of `flutter doctor` so we can best help you.

**Comment by cbenhagen** [comment]
Closing this. Without any details we are not able to fix anything. Please reopen a new issue with a sample `main.dart` file and any info that might help us reproduce the issue.
