### ISSUE TITLE
Unable to open some mp4 on Samsung SM-T700

### ISSUE THREAD

**Issue by Stampede10343** [brianegan/chewie#78]
`E/ExoPlayerImplInternal( 8352): Playback error.
E/ExoPlayerImplInternal( 8352): com.google.android.exoplayer2.ExoPlaybackException
E/ExoPlayerImplInternal( 8352): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:441)
E/ExoPlayerImplInternal( 8352): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:428)
E/ExoPlayerImplInternal( 8352): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:920)
E/ExoPlayerImplInternal( 8352): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:503)
E/ExoPlayerImplInternal( 8352): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:557)
E/ExoPlayerImplInternal( 8352): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
E/ExoPlayerImplInternal( 8352): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
E/ExoPlayerImplInternal( 8352): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 8352): 	at android.os.Looper.loop(Looper.java:148)
E/ExoPlayerImplInternal( 8352): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 8352): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, video/avc, -1, null, [3840, 2160, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 8352): 	... 9 more
E/ExoPlayerImplInternal( 8352): Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
E/ExoPlayerImplInternal( 8352): 	at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal( 8352): 	at android.media.MediaCodec.configure(MediaCodec.java:1778)
E/ExoPlayerImplInternal( 8352): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:450)
E/ExoPlayerImplInternal( 8352): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:418)
E/ExoPlayerImplInternal( 8352): 	... 8 more`

It appears to be an issue with the codec, the video opens on the Android emulator and a Pixel XL fine as well as normal PC/web clients.

**Comment by Sub6Resources** [comment]
This is most likely an issue with the device itself or the video files, so there's not a whole lot Chewie can do to fix this issue.

**Comment by brianegan** [comment]
Hey there, for codec issues, could you please file a bug against the `video_player` package? This library is really just a skin for that package.
