### ISSUE TITLE
Audio works but video is not appearing...

### ISSUE THREAD

**Issue by sebasbose** [brianegan/chewie#85]
The videos audio works, the timeline works, the buttons work, but the video doesn't display.

**Comment by Sub6Resources** [comment]
Please give some more info: maybe file type, device, flutter version, result of `flutter doctor`

**Comment by sebasbose** [comment]
Sure, it is on an iPhone, latest Flutter version, the file type mp4 (maybe here is the problem). 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.3-pre.13, on Mac OS X 10.14.2 18C54, locale es-CR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by Sub6Resources** [comment]
Hmm, looks okay. Have you tried any other files? If that's not the issue, does the video file play okay in the `video_player` plugin itself?

**Comment by Mil0R** [comment]
@sebasbose you test it on device or simulator? I fount it does not appear on simulator, but normal on device.

**Comment by sebasbose** [comment]
That might be the problem since I tested it on simulator and didn't try it on iPhone... any idea why this happens?

**Comment by cbenhagen** [comment]
This is a known limitation of the video_player plug-in. You can watch this issue: https://github.com/flutter/flutter/issues/14647

**Comment by alexrabin** [comment]
I'm having this issue on an actual device on iOS 14
