### ISSUE TITLE
Replay button on video finish

### ISSUE THREAD

**Issue by lodemo** [brianegan/chewie#88]
Hello,
i think it would make sense to display either a replay button when the video finished (and looping is false), or reset the video to the start and display the play button again. 
At the moment, at least for me, the video just ends and we have to manually slide the progress indicator back to the start if you want to watch it again.

**Comment by Leffe108** [comment]
I think when the video ends this should happen:
* Play/pause button turns into a play button that will seek to time 0 and play again when tapped.
* Controls will auto show.

I use the video player for short clips that user likely want to watch again. But are there cases where one of the above behaviours would be wrong? Maybe auto-showing of controls is not desired in some apps?

**Comment by KarenKaKa** [comment]
same issue

**Comment by mabinici** [comment]
Any updates on this?

**Comment by VictorUvarov** [comment]
This video player has a lot more functionality including replay. https://github.com/CaiJingLong/flutter_ijkplayer

**Comment by manikandn** [comment]
@brianegan Please review my PR and let me know if any changes are required.
