### ISSUE TITLE
How to stop video,audio on back pressed.

### ISSUE THREAD

**Issue by gauravsingla05** [brianegan/chewie#92]
I'm using this widget on the second page. When I press the back button, the video does not stop. It keeps on playing in the background.

**Comment by robin7331** [comment]
You could wrap your Widget containing the VideoPlayer in a ```WillPopScope()``` to receive the back button callback like so:

```
@override
  Widget build(BuildContext context) {
    return WillPopScope(
        onWillPop: () {
          if (_controller.controller.value.isPlaying) {
            _controller.controller.pause();
          }
          return new Future.value(true);
        },
        child: Scaffold( /** Your video_player lives here */)
        },
    );
  }

```

**Comment by cbenhagen** [comment]
@gauravsingla05 the tips above should provide you with enough information to make it work. I am closing this issue. If you feel there is something wrong with `Chewie`, please open a new issue with a simple example and the output of `flutter doctor`.
