### ISSUE TITLE
Using chewie in ListView error occurs.

### ISSUE THREAD

**Issue by and1990** [brianegan/chewie#94]
Everything was ok when the app started, some error occurred when I scrolled the view from top to the end quickly on my android phone. But it's ok on the Android device emulator.
Full error report, check out the error file. Help me, please.
[error.txt](https://github.com/brianegan/chewie/files/2743898/error.txt)

**Comment by brianegan** [comment]
Hey there -- looks like there's some codec issue here: `codec does not support config priority (err -2147483648)
I/OMXClient`. On Android, that could mean a number of things.

Either way, this package uses the `video_player` plugin under the hood and delegates all of the playback responsibilities to that plugin, including codecs and all that. Could you please file an issue on that repo instead?
