### ISSUE TITLE
Chewie ^0.8.0 does not support the latest VideoPlayer version ^0.8.0

### ISSUE THREAD

**Issue by fritz-playmaker** [brianegan/chewie#95]
`flutter packages get
Running "flutter packages get" in opine-app...                  
Because chewie 0.8.0 depends on video_player ^0.7.0 and no versions of chewie match >0.8.0 <0.9.0, chewie ^0.8.0 requires video_player ^0.7.0.
So, because opine_app depends on both video_player ^0.8.0 and chewie ^0.8.0, version solving failed.

pub get failed (1)
exit code 1`

**Comment by Gazler** [comment]
I've opened a PR for this here https://github.com/brianegan/chewie/pull/97

**Comment by cbenhagen** [comment]
The PR has been merged. Thanks @Gazler.
